In [1]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_csv('../../Documents/Ironhack/Slides/vehicles/vehicles/vehicles.csv')

In [8]:
df.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

# Groupby

select agg_func(column)
from table
group by column2

In [10]:
groups=df.groupby('Transmission')

In [11]:
for i,j in groups:
    print(i)
    display(j)

Auto (AV)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
7911,Chevrolet,Volt,2011,1.4,4.0,Auto (AV),Front-Wheel Drive,Compact Cars,Premium Gas or Electricity,3.375621,35,40,37,84.0,1100
7912,Chevrolet,Volt,2012,1.4,4.0,Auto (AV),Front-Wheel Drive,Compact Cars,Premium Gas or Electricity,3.375621,35,40,37,87.0,1100

Auto (AV-S6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
21220,Lexus,GS 450h,2010,3.5,6.0,Auto (AV-S6),Rear-Wheel Drive,Compact Cars,Premium,14.33087,22,25,23,386.391304,1750

Auto (AV-S8)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
21372,Lexus,LS 600h L,2010,5.0,8.0,Auto (AV-S8),All-Wheel Drive,Midsize Cars,Premium,15.695714,20,22,21,423.190476,1950

Auto(A1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.56319,41,37,39,40.0,1050

Auto(AM-S6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
634,Audi,A3,2013,2.0,4.0,Auto(AM-S6),Front-Wheel Drive,Small Station Wagons,Premium,13.733750,21,28,24,381.0,1700
635,Audi,A3,2013,2.0,4.0,Auto(AM-S6),Front-Wheel Drive,Small Station Wagons,Diesel,11.240735,30,42,34,297.0,1050
636,Audi,A3,2015,1.8,4.0,Auto(AM-S6),Front-Wheel Drive,Subcompact Cars,Premium,12.207778,23,33,27,328.0,1500
637,Audi,A3,2015,2.0,4.0,Auto(AM-S6),Front-Wheel Drive,Subcompact Cars,Diesel,10.616250,31,43,36,285.0,1000
638,Audi,A3,2016,1.8,4.0,Auto(AM-S6),Front-Wheel Drive,Subcompact Cars,Regular,12.207778,23,33,27,328.0,1250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34915,Volkswagen,Passat,2014,2.0,4.0,Auto(AM-S6),Front-Wheel Drive,Midsize Cars,Diesel,11.240735,30,40,34,290.0,1050
34921,Volkswagen,Passat,2015,3.6,6.0,Auto(AM-S6),Front-Wheel Drive,Midsize Cars,Premium,14.330870,20,28,23,390.0,1750
34923,Volkswagen,Passat,2015,2.0,4.0,Auto(AM-S6),Front-Wheel Drive,Midsize Cars,Diesel,11.240735,30,42,34,298.0,1050
34926,Volkswagen,Passat,2016,3.6,6.0,Auto(AM-S6),Front-Wheel Drive,Midsize Cars,Regular,14.330870,20,28,23,390.0,1450
34928,Volkswagen,Passat,2017,3.6,6.0,Auto(AM-S6),Front-Wheel Drive,Midsize Cars,Regular,14.330870,20,28,23,390.0,1450

Auto(AM-S7)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
206,Acura,RLX Hybrid,2017,3.5,6.0,Auto(AM-S7),All-Wheel Drive,Midsize Cars,Premium,11.365862,29,30,29,306.0,1400
708,Audi,A4,2017,2.0,4.0,Auto(AM-S7),Front-Wheel Drive,Compact Cars,Premium,11.771786,25,33,28,315.0,1450
779,Audi,A4 Ultra,2017,2.0,4.0,Auto(AM-S7),Front-Wheel Drive,Compact Cars,Premium,10.632581,27,37,31,284.0,1300
780,Audi,A4 allroad quattro,2017,2.0,4.0,Auto(AM-S7),All-Wheel Drive,Small Station Wagons,Premium,13.184400,23,28,25,349.0,1600
851,Audi,A4 quattro,2017,2.0,4.0,Auto(AM-S7),All-Wheel Drive,Compact Cars,Premium,12.207778,24,31,27,330.0,1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29813,Porsche,Panamera Turbo S Executive,2016,4.8,8.0,Auto(AM-S7),All-Wheel Drive,Large Cars,Premium,18.311667,15,24,18,488.0,2250
34664,Volkswagen,Jetta Hybrid,2013,1.4,4.0,Auto(AM-S7),Front-Wheel Drive,Compact Cars,Premium,7.324667,42,48,45,200.0,900
34665,Volkswagen,Jetta Hybrid,2014,1.4,4.0,Auto(AM-S7),Front-Wheel Drive,Compact Cars,Premium,7.324667,42,48,45,200.0,900
34666,Volkswagen,Jetta Hybrid,2015,1.4,4.0,Auto(AM-S7),Front-Wheel Drive,Compact Cars,Premium,7.324667,42,48,45,200.0,900
34667,Volkswagen,Jetta Hybrid,2016,1.4,4.0,Auto(AM-S7),Front-Wheel Drive,Compact Cars,Premium,7.491136,42,48,44,200.0,900

Auto(AM-S8)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
46,Acura,ILX,2017,2.4,4.0,Auto(AM-S8),Front-Wheel Drive,Compact Cars,Premium,11.365862,25,35,29,309.0,1400
259,Acura,TLX 2WD,2016,2.4,4.0,Auto(AM-S8),Front-Wheel Drive,Compact Cars,Premium,11.771786,24,35,28,316.0,1450
264,Acura,TLX FWD,2017,2.4,4.0,Auto(AM-S8),Front-Wheel Drive,Compact Cars,Premium,11.771786,24,35,28,321.0,1450
29791,Porsche,Panamera S E-Hybrid,2014,3.0,6.0,Auto(AM-S8),Rear-Wheel Drive,Large Cars,Premium and Electricity,8.099619,23,29,25,206.0,1600
29792,Porsche,Panamera S E-Hybrid,2015,3.0,6.0,Auto(AM-S8),Rear-Wheel Drive,Large Cars,Premium and Electricity,8.076981,23,29,25,229.0,1600
29793,Porsche,Panamera S E-Hybrid,2016,3.0,6.0,Auto(AM-S8),Rear-Wheel Drive,Large Cars,Premium and Electricity,7.984573,23,29,25,229.0,1600

Auto(AM-S9)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
172,Acura,NSX Hybrid,2017,3.5,6.0,Auto(AM-S9),All-Wheel Drive,Two Seaters,Premium,15.695714,21,22,21,420.0,1950

Auto(AM5)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
35932,smart,fortwo cabriolet,2010,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100
35933,smart,fortwo cabriolet,2011,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100
35934,smart,fortwo cabriolet,2012,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,246.861111,1100
35935,smart,fortwo cabriolet,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35936,smart,fortwo cabriolet,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35937,smart,fortwo cabriolet,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35944,smart,fortwo coupe,2010,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100
35945,smart,fortwo coupe,2011,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100
35946,smart,fortwo coupe,2012,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,246.861111,1100
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100

Auto(AM6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
320,Alfa Romeo,4C,2015,1.8,4.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,11.771786,24,34,28,317.0000,1450
321,Alfa Romeo,4C,2016,1.8,4.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,11.771786,24,34,28,317.0000,1450
460,Aston Martin,V8 Vantage,2010,4.7,8.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,20.600625,14,20,16,555.4375,2550
463,Aston Martin,V8 Vantage,2011,4.7,8.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,20.600625,14,20,16,555.4375,2550
465,Aston Martin,V8 Vantage,2012,4.7,8.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,20.600625,14,20,16,555.4375,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26489,Nissan,GT-R,2015,3.8,6.0,Auto(AM6),All-Wheel Drive,Subcompact Cars,Premium,17.347895,16,23,19,472.0000,2150
26490,Nissan,GT-R,2016,3.8,6.0,Auto(AM6),All-Wheel Drive,Subcompact Cars,Premium,17.347895,16,22,19,474.0000,2150
26491,Nissan,GT-R,2017,3.8,6.0,Auto(AM6),All-Wheel Drive,Subcompact Cars,Premium,18.311667,16,22,18,484.0000,2250
35938,smart,fortwo cabriolet,2017,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.417429,33,38,35,251.0000,1150
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.0000,1100

Auto(AM7)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
205,Acura,RLX Hybrid,2016,3.5,6.0,Auto(AM7),All-Wheel Drive,Midsize Cars,Premium,10.987000,28,32,30,297.0000,1350
450,Aston Martin,V12 Vantage S,2015,6.0,12.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,23.543571,12,18,14,628.0000,2900
451,Aston Martin,V12 Vantage S,2016,6.0,12.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,23.543571,12,18,14,628.0000,2900
452,Aston Martin,V12 Vantage S,2017,6.0,12.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,23.543571,12,18,14,624.0000,2900
466,Aston Martin,V8 Vantage,2012,4.7,8.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,20.600625,14,21,16,555.4375,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24531,Mercedes-Benz,SLS AMG Roadster,2012,6.2,8.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,20.600625,14,20,16,555.4375,2550
24532,Mercedes-Benz,SLS AMG Roadster,2013,6.2,8.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,21.974000,13,19,15,592.0000,2700
24533,Mercedes-Benz,SLS AMG Roadster,2014,6.2,8.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,21.974000,13,19,15,592.0000,2700
27668,Pagani,Huayra Coupe,2014,6.0,12.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,25.354615,11,17,13,671.0000,3100
27669,Pagani,Huayra Coupe,2016,6.0,12.0,Auto(AM7),Rear-Wheel Drive,Two Seaters,Premium,25.354615,11,17,13,671.0000,3100

Auto(AM8)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
45,Acura,ILX,2016,2.4,4.0,Auto(AM8),Front-Wheel Drive,Compact Cars,Premium,11.365862,25,36,29,305.0,1400
257,Acura,TLX,2015,2.4,4.0,Auto(AM8),Front-Wheel Drive,Compact Cars,Premium,11.771786,24,35,28,316.0,1450
29670,Porsche,Cayenne S e-Hybrid,2015,3.0,6.0,Auto(AM8),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium Gas or Electricity,9.532027,21,24,22,260.0,1850
29671,Porsche,Cayenne S e-Hybrid,2016,3.0,6.0,Auto(AM8),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium Gas or Electricity,9.532027,21,24,22,260.0,1850
29672,Porsche,Cayenne S e-Hybrid,2017,3.0,6.0,Auto(AM8),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium Gas or Electricity,9.535201,21,24,22,258.0,1850

Auto(AV-S6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
3382,Buick,LaCrosse eAssist,2012,2.4,4.0,Auto(AV-S6),Front-Wheel Drive,Midsize Cars,Regular,11.365862,25,36,29,306.448276,1150
3574,Buick,Regal eAssist,2012,2.4,4.0,Auto(AV-S6),Front-Wheel Drive,Midsize Cars,Regular,11.365862,25,36,29,306.448276,1150
18572,Infiniti,JX35 AWD,2013,3.5,6.0,Auto(AV-S6),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,16.480500,18,23,20,443.000000,2000
18573,Infiniti,JX35 FWD,2013,3.5,6.0,Auto(AV-S6),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,15.695714,18,24,21,432.000000,1950
21153,Lexus,ES 300h,2013,2.5,4.0,Auto(AV-S6),Front-Wheel Drive,Midsize Cars,Regular,8.240250,40,39,40,224.000000,850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33099,Toyota,Highlander Hybrid 4WD LE Plus,2014,3.5,6.0,Auto(AV-S6),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Regular,11.771786,28,28,28,313.000000,1200
33100,Toyota,Highlander Hybrid 4WD LE Plus,2015,3.5,6.0,Auto(AV-S6),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Regular,11.771786,28,28,28,313.000000,1200
33101,Toyota,Highlander Hybrid 4WD LE Plus,2016,3.5,6.0,Auto(AV-S6),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Regular,11.771786,28,28,28,313.000000,1200
33374,Toyota,RAV4 Hybrid AWD,2016,2.5,4.0,Auto(AV-S6),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Regular,9.988182,34,31,33,270.000000,1000
33375,Toyota,RAV4 Hybrid AWD,2017,2.5,4.0,Auto(AV-S6),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Regular,10.300313,34,30,32,275.000000,1050

Auto(AV-S7)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
47,Acura,ILX Hybrid,2013,1.5,4.0,Auto(AV-S7),Front-Wheel Drive,Compact Cars,Premium,8.673947,39,38,38,228.0,1050
48,Acura,ILX Hybrid,2014,1.5,4.0,Auto(AV-S7),Front-Wheel Drive,Compact Cars,Premium,8.673947,39,38,38,228.0,1050
16999,Honda,Accord,2013,2.4,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,11.365862,26,35,29,303.0,1150
17005,Honda,Accord,2014,2.4,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,11.365862,26,34,29,304.0,1150
17016,Honda,Accord,2015,2.4,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,11.365862,26,35,29,302.0,1150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32915,Toyota,Corolla,2014,1.8,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,10.300313,29,37,32,275.0,1050
32920,Toyota,Corolla,2015,1.8,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,10.300313,29,37,32,278.0,1050
32922,Toyota,Corolla,2016,1.8,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,10.300313,29,37,32,277.0,1050
32927,Toyota,Corolla,2017,1.8,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,10.632581,28,35,31,286.0,1050
32980,Toyota,Corolla iM,2017,1.8,4.0,Auto(AV-S7),Front-Wheel Drive,Midsize Cars,Regular,10.632581,28,36,31,283.0,1050

Auto(AV-S8)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
704,Audi,A4,2013,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Compact Cars,Premium,12.677308,24,31,26,342.00,1550
705,Audi,A4,2014,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Compact Cars,Premium,12.207778,24,32,27,333.00,1500
706,Audi,A4,2015,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Compact Cars,Premium,12.207778,24,32,27,332.00,1500
707,Audi,A4,2016,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Compact Cars,Premium,12.207778,24,31,27,341.00,1500
855,Audi,A5 Cabriolet,2013,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Subcompact Cars,Premium,12.677308,24,31,26,342.00,1550
856,Audi,A5 Cabriolet,2014,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Subcompact Cars,Premium,12.207778,24,32,27,333.00,1500
906,Audi,A6,2013,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Midsize Cars,Premium,11.771786,25,33,28,320.00,1450
907,Audi,A6,2014,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Midsize Cars,Premium,11.771786,25,33,28,320.00,1450
908,Audi,A6,2015,2.0,4.0,Auto(AV-S8),Front-Wheel Drive,Midsize Cars,Premium,11.771786,25,33,28,320.00,1450
21223,Lexus,GS 450h,2014,3.5,6.0,Auto(AV-S8),Rear-Wheel Drive,Midsize Cars,Premium,10.632581,29,34,31,283.00,1300
21224,Lexus,GS 450h,2015,3.5,6.0,Auto(AV-S8),Rear-Wheel Drive,Midsize Cars,Premium,10.632581,29,34,31,283.00,1300
21225,Lexus,GS 450h,2016,3.5,6.0,Auto(AV-S8),Rear-Wheel Drive,Midsize Cars,Premium,10.632581,29,34,31,283.00,1300
21373,Lexus,LS 600h L,2011,5.0,8.0,Auto(AV-S8),All-Wheel Drive,Midsize Cars,Premium,16.480500,19,23,20,444.35,2000
21374,Lexus,LS 600h L,2012,5.0,8.0,Auto(AV-S8),All-Wheel Drive,Midsize Cars,Premium,16.480500,19,23,20,444.35,2000
21375,Lexus,LS 600h L,2013,5.0,8.0,Auto(AV-S8),All-Wheel Drive,Midsize Cars,Premium,16.480500,19,23,20,432.00,2000
21376,Lexus,LS 600h L,2014,5.0,8.0,Auto(AV-S8),All-Wheel Drive,Midsize Cars,Premium,16.480500,19,23,20,432.00,2000
21377,Lexus,LS 600h L,2015,5.0,8.0,Auto(AV-S8),All-Wheel Drive,Midsize Cars,Premium,16.480500,19,23,20,432.00,2000
21378,Lexus,LS 600h L,2016,5.0,8.0,Auto(AV-S8),All-Wheel Drive,Midsize Cars,Premium,16.480500,19,23,20,431.00,2000
26519,Nissan,Juke Nismo RS AWD,2015,1.6,4.0,Auto(AV-S8),All-Wheel Drive,Small Station Wagons,Premium,12.207778,25,29,27,334.00,1500
26520,Nissan,Juke Nismo RS AWD,2016,1.6,4.0,Auto(AV-S8),All-Wheel Drive,Small Station Wagons,Premium,12.207778,25,29,27,334.00,1500
31063,Subaru,Forester AWD,2015,2.0,4.0,Auto(AV-S8),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.184400,23,28,25,357.00,1600
31066,Subaru,Forester AWD,2016,2.0,4.0,Auto(AV-S8),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.184400,23,28,25,357.00,1600
31067,Subaru,Forester AWD,2017,2.0,4.0,Auto(AV-S8),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.184400,23,27,25,359.00,1600
31638,Subaru,WRX,2015,2.0,4.0,Auto(AV-S8),All-Wheel Drive,Compact Cars,Premium,15.695714,19,25,21,405.00,1950
31641,Subaru,WRX,2016,2.0,4.0,Auto(AV-S8),All-Wheel Drive,Compact Cars,Premium,15.695714,18,24,21,419.00,1950
31643,Subaru,WRX,2017,2.0,4.0,Auto(AV-S8),All-Wheel Drive,Compact Cars,Premium,15.695714,18,24,21,420.00,1950

Auto(L3)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
20319,Jeep,Wrangler 4WD,1997,2.5,4.0,Auto(L3),4-Wheel Drive,Special Purpose Vehicles,Regular,20.600625,15,18,16,555.437500,2100
20321,Jeep,Wrangler 4WD,1997,4.0,6.0,Auto(L3),4-Wheel Drive,Special Purpose Vehicles,Regular,21.974000,13,16,15,592.466667,2200

Auto(L4)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
19622,Jeep,Cherokee 2WD,1997,4.0,6.0,Auto(L4),Rear-Wheel Drive,Special Purpose Vehicles,Regular,20.600625,14,20,16,555.437500,2100
19664,Jeep,Cherokee 4WD,1997,4.0,6.0,Auto(L4),4-Wheel Drive,Special Purpose Vehicles,Regular,21.974000,13,18,15,592.466667,2200

Automatic (A1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,40.0,1050
3071,BMW,i3 REX,2016,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,41,37,39,37.0,1050
11439,Fisker,Karma,2012,2.0,4.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,6.359255,20,21,20,169.0,2000

Automatic (A6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
3105,Bentley,Azure,2010,6.8,8.0,Automatic (A6),Rear-Wheel Drive,Compact Cars,Premium,29.964545,9,15,11,807.909091,3700
3108,Bentley,Brooklands,2010,6.8,8.0,Automatic (A6),Rear-Wheel Drive,Compact Cars,Premium,29.964545,9,15,11,807.909091,3700
13448,Ford,Fusion FWD FFV,2010,3.0,6.0,Automatic (A6),Front-Wheel Drive,Midsize Cars,Gasoline or E85,14.982273,19,27,22,403.954545,1500
24751,Mercury,Milan FFV,2010,3.0,6.0,Automatic (A6),Front-Wheel Drive,Midsize Cars,Gasoline or E85,14.982273,19,27,22,403.954545,1500

Automatic (AM5)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
35941,smart,fortwo convertible,2009,1.0,3.0,Automatic (AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100
35943,smart,fortwo coupe,2009,1.0,3.0,Automatic (AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100

Automatic (AM6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
1140,Audi,R8,2010,4.2,8.0,Automatic (AM6),All-Wheel Drive,Two Seaters,Premium,21.974,13,18,15,592.466667,2700

Automatic (AV)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
703,Audi,A4,2012,2.0,4.0,Automatic (AV),Front-Wheel Drive,Compact Cars,Premium,13.184400,22,30,25,355.480000,1600
854,Audi,A5 Cabriolet,2012,2.0,4.0,Automatic (AV),Front-Wheel Drive,Subcompact Cars,Premium,13.184400,22,30,25,355.480000,1600
902,Audi,A6,2009,3.1,6.0,Automatic (AV),Front-Wheel Drive,Midsize Cars,Premium,15.695714,18,27,21,423.190476,1950
905,Audi,A6,2012,2.0,4.0,Automatic (AV),Front-Wheel Drive,Midsize Cars,Premium,11.771786,25,33,28,317.392857,1450

Automatic (AV-S6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
21477,Lexus,RX 450h,2010,3.5,6.0,Automatic (AV-S6),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Premium,10.987000,32,28,30,296.233333,1350
21484,Lexus,RX 450h AWD,2010,3.5,6.0,Automatic (AV-S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,11.365862,30,28,29,306.448276,1400
25494,Mitsubishi,Lancer,2010,2.4,4.0,Automatic (AV-S6),Front-Wheel Drive,Compact Cars,Regular,13.184400,22,29,25,355.480000,1350
25495,Mitsubishi,Lancer,2010,2.0,4.0,Automatic (AV-S6),Front-Wheel Drive,Compact Cars,Regular,12.677308,23,30,26,341.807692,1300
25563,Mitsubishi,Lancer Sportback,2010,2.4,4.0,Automatic (AV-S6),Front-Wheel Drive,Small Station Wagons,Regular,14.330870,21,27,23,386.391304,1450
25795,Mitsubishi,Outlander 2WD,2010,2.4,4.0,Automatic (AV-S6),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Regular,13.733750,21,27,24,370.291667,1400
25817,Mitsubishi,Outlander 4WD,2010,2.4,4.0,Automatic (AV-S6),4-Wheel Drive,Sport Utility Vehicle - 4WD,Regular,14.982273,21,25,22,403.954545,1500
26572,Nissan,Maxima,2010,3.5,6.0,Automatic (AV-S6),Front-Wheel Drive,Midsize Cars,Premium,14.982273,19,26,22,403.954545,1850
26911,Nissan,Sentra,2010,2.5,4.0,Automatic (AV-S6),Front-Wheel Drive,Midsize Cars,Regular,12.677308,24,30,26,341.807692,1300

Automatic (S4)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
162,Acura,NSX,2001,3.0,6.0,Automatic (S4),Rear-Wheel Drive,Two Seaters,Premium,18.311667,15,22,18,493.722222,2250
164,Acura,NSX,2002,3.0,6.0,Automatic (S4),Rear-Wheel Drive,Two Seaters,Premium,18.311667,15,22,18,493.722222,2250
166,Acura,NSX,2003,3.0,6.0,Automatic (S4),Rear-Wheel Drive,Two Seaters,Premium,18.311667,15,22,18,493.722222,2250
168,Acura,NSX,2004,3.0,6.0,Automatic (S4),Rear-Wheel Drive,Two Seaters,Premium,18.311667,16,22,18,493.722222,2250
170,Acura,NSX,2005,3.0,6.0,Automatic (S4),Rear-Wheel Drive,Two Seaters,Premium,18.311667,16,22,18,493.722222,2250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35647,Volvo,S80/S80 Executive,2003,2.9,6.0,Automatic (S4),Front-Wheel Drive,Midsize Cars,Premium,17.347895,17,24,19,467.736842,2150
35650,Volvo,S80/S80 Premier,2004,2.9,6.0,Automatic (S4),Front-Wheel Drive,Midsize Cars,Premium,17.347895,17,24,19,467.736842,2150
35807,Volvo,XC 90 AWD,2003,2.9,6.0,Automatic (S4),4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,20.600625,14,19,16,555.437500,2550
35809,Volvo,XC 90 AWD,2004,2.9,6.0,Automatic (S4),4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,20.600625,14,19,16,555.437500,2550
35811,Volvo,XC 90 AWD,2005,2.9,6.0,Automatic (S4),4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,20.600625,14,19,16,555.437500,2550

Automatic (S5)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
21,Acura,3.2CL,2001,3.2,6.0,Automatic (S5),Front-Wheel Drive,Compact Cars,Premium,16.480500,17,27,20,444.350000,2000
22,Acura,3.2CL,2002,3.2,6.0,Automatic (S5),Front-Wheel Drive,Compact Cars,Premium,15.695714,17,27,21,423.190476,1950
24,Acura,3.2CL,2003,3.2,6.0,Automatic (S5),Front-Wheel Drive,Compact Cars,Premium,15.695714,17,27,21,423.190476,1950
27,Acura,3.2TL,2001,3.2,6.0,Automatic (S5),Front-Wheel Drive,Midsize Cars,Premium,16.480500,17,27,20,444.350000,2000
28,Acura,3.2TL,2002,3.2,6.0,Automatic (S5),Front-Wheel Drive,Midsize Cars,Premium,15.695714,17,27,21,423.190476,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35826,Volvo,XC 90 FWD,2005,2.5,5.0,Automatic (S5),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Premium,18.311667,16,21,18,493.722222,2250
35827,Volvo,XC 90 FWD,2006,2.5,5.0,Automatic (S5),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Premium,18.311667,15,21,18,493.722222,2250
35828,Volvo,XC 90 FWD,2007,2.5,5.0,Automatic (S5),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Premium,18.311667,15,21,18,493.722222,2250
35940,smart,fortwo convertible,2008,1.0,3.0,Automatic (S5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100
35942,smart,fortwo coupe,2008,1.0,3.0,Automatic (S5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,33,41,36,246.861111,1100

Automatic (S6)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
121,Acura,MDX 2WD,2014,3.5,6.0,Automatic (S6),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,14.330870,20,28,23,387.000000,1750
122,Acura,MDX 2WD,2015,3.5,6.0,Automatic (S6),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,14.330870,20,28,23,387.000000,1750
132,Acura,MDX 4WD,2010,3.7,6.0,Automatic (S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,18.311667,16,21,18,493.722222,2250
133,Acura,MDX 4WD,2011,3.7,6.0,Automatic (S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,18.311667,16,21,18,493.722222,2250
134,Acura,MDX 4WD,2012,3.7,6.0,Automatic (S6),All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,18.311667,16,21,18,493.722222,2250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35879,Volvo,XC90 AWD,2014,3.2,6.0,Automatic (S6),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Regular,18.311667,16,23,18,473.000000,1850
35886,Volvo,XC90 FWD,2011,3.2,6.0,Automatic (S6),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Regular,18.311667,16,22,18,493.722222,1850
35887,Volvo,XC90 FWD,2012,3.2,6.0,Automatic (S6),Front-Wheel Drive,Sport Utility Vehicle - 2WD,Regular,17.347895,16,23,19,467.736842,1750
35888,Volvo,XC90 FWD,2013,3.2,6.0,Automatic (S6),Front-Wheel Drive,Standard Sport Utility Vehicle 2WD,Regular,17.347895,16,23,19,472.000000,1750
35889,Volvo,XC90 FWD,2014,3.2,6.0,Automatic (S6),Front-Wheel Drive,Standard Sport Utility Vehicle 2WD,Regular,17.347895,16,25,19,454.000000,1750

Automatic (S7)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
204,Acura,RLX Hybrid,2014,3.5,6.0,Automatic (S7),All-Wheel Drive,Midsize Cars,Premium,10.987000,28,32,30,298.000000,1350
1211,Audi,S4,2010,3.0,6.0,Automatic (S7),All-Wheel Drive,Compact Cars,Premium,15.695714,18,28,21,423.190476,1950
1213,Audi,S4,2011,3.0,6.0,Automatic (S7),All-Wheel Drive,Compact Cars,Premium,15.695714,18,28,21,423.190476,1950
1215,Audi,S4,2012,3.0,6.0,Automatic (S7),All-Wheel Drive,Compact Cars,Premium,15.695714,18,28,21,423.190476,1950
1271,Audi,S5 Cabriolet,2010,3.0,6.0,Automatic (S7),All-Wheel Drive,Subcompact Cars,Premium,16.480500,17,26,20,444.350000,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26308,Nissan,Armada 2WD,2017,5.6,8.0,Automatic (S7),Rear-Wheel Drive,Standard Sport Utility Vehicle 2WD,Regular,20.600625,14,19,16,555.000000,2100
26329,Nissan,Armada 4WD,2017,5.6,8.0,Automatic (S7),4-Wheel Drive,Standard Sport Utility Vehicle 4WD,Regular,21.974000,13,18,15,588.000000,2200
27036,Nissan,Titan 2WD,2017,5.6,8.0,Automatic (S7),Rear-Wheel Drive,Standard Pickup Trucks 2WD,Regular,18.311667,15,21,18,505.000000,1850
27060,Nissan,Titan 4WD,2017,5.6,8.0,Automatic (S7),Part-time 4-Wheel Drive,Standard Pickup Trucks 4WD,Regular,18.311667,15,21,18,505.000000,1850
27061,Nissan,Titan 4WD PRO4X,2017,5.6,8.0,Automatic (S7),Part-time 4-Wheel Drive,Standard Pickup Trucks 4WD,Regular,19.388824,15,20,17,529.000000,1950

Automatic (S8)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
434,Aston Martin,Rapide S,2015,6.0,12.0,Automatic (S8),Rear-Wheel Drive,Subcompact Cars,Premium,19.388824,14,22,17,534.0,2400
435,Aston Martin,Rapide S,2016,6.0,12.0,Automatic (S8),Rear-Wheel Drive,Subcompact Cars,Premium,19.388824,14,22,17,534.0,2400
436,Aston Martin,Rapide S,2017,6.0,12.0,Automatic (S8),Rear-Wheel Drive,Subcompact Cars,Premium,19.388824,14,21,17,533.0,2400
489,Aston Martin,Vanquish,2015,6.0,12.0,Automatic (S8),Rear-Wheel Drive,Minicompact Cars,Premium,20.600625,13,21,16,557.0,2550
490,Aston Martin,Vanquish,2016,6.0,12.0,Automatic (S8),Rear-Wheel Drive,Minicompact Cars,Premium,20.600625,13,21,16,557.0,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35883,Volvo,XC90 AWD,2017,2.0,4.0,Automatic (S8),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium,14.330870,22,25,23,384.0,1750
35884,Volvo,XC90 AWD PHEV,2016,2.0,4.0,Automatic (S8),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium and Electricity,8.670674,24,27,25,241.0,1600
35885,Volvo,XC90 AWD PHEV,2017,2.0,4.0,Automatic (S8),All-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium and Electricity,8.652550,24,27,25,238.0,1600
35890,Volvo,XC90 FWD,2016,2.0,4.0,Automatic (S8),Front-Wheel Drive,Standard Sport Utility Vehicle 2WD,Premium,13.733750,22,26,24,373.0,1700
35891,Volvo,XC90 FWD,2017,2.0,4.0,Automatic (S8),Front-Wheel Drive,Standard Sport Utility Vehicle 2WD,Premium,13.733750,22,26,24,373.0,1700

Automatic (S9)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
123,Acura,MDX 2WD,2016,3.5,6.0,Automatic (S9),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,14.330870,20,27,23,390.0,1750
124,Acura,MDX 2WD,2016,3.5,6.0,Automatic (S9),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,14.982273,19,27,22,403.0,1850
138,Acura,MDX 4WD,2016,3.5,6.0,Automatic (S9),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,14.982273,19,26,22,409.0,1850
139,Acura,MDX 4WD,2016,3.5,6.0,Automatic (S9),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,15.695714,18,26,21,412.0,1950
140,Acura,MDX AWD,2017,3.5,6.0,Automatic (S9),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,14.982273,19,26,22,404.0,1850
141,Acura,MDX AWD,2017,3.5,6.0,Automatic (S9),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,15.695714,18,26,21,424.0,1950
142,Acura,MDX FWD,2017,3.5,6.0,Automatic (S9),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,14.330870,20,27,23,391.0,1750
143,Acura,MDX FWD,2017,3.5,6.0,Automatic (S9),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Premium,14.982273,19,27,22,404.0,1850
258,Acura,TLX,2015,3.5,6.0,Automatic (S9),Front-Wheel Drive,Compact Cars,Premium,13.184400,21,34,25,358.0,1600
260,Acura,TLX 2WD,2016,3.5,6.0,Automatic (S9),Front-Wheel Drive,Compact Cars,Premium,13.184400,21,34,25,358.0,1600
261,Acura,TLX 4WD,2016,3.5,6.0,Automatic (S9),All-Wheel Drive,Compact Cars,Premium,13.184400,21,31,25,357.0,1600
262,Acura,TLX AWD,2015,3.5,6.0,Automatic (S9),All-Wheel Drive,Compact Cars,Premium,13.184400,21,31,25,357.0,1600
263,Acura,TLX AWD,2017,3.5,6.0,Automatic (S9),All-Wheel Drive,Compact Cars,Premium,13.184400,21,31,25,358.0,1600
265,Acura,TLX FWD,2017,3.5,6.0,Automatic (S9),Front-Wheel Drive,Compact Cars,Premium,13.184400,21,34,25,358.0,1600
17626,Honda,Pilot 2WD,2016,3.5,6.0,Automatic (S9),Front-Wheel Drive,Small Sport Utility Vehicle 2WD,Regular,14.330870,20,27,23,386.0,1450
17641,Honda,Pilot 4WD,2016,3.5,6.0,Automatic (S9),All-Wheel Drive,Small Sport Utility Vehicle 4WD,Regular,14.982273,19,26,22,405.0,1500
21006,Land Rover,Discovery Sport,2015,2.0,4.0,Automatic (S9),4-Wheel Drive,Standard Sport Utility Vehicle 4WD,Premium,14.982273,20,26,22,399.0,1850
21007,Land Rover,Discovery Sport,2016,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,14.982273,20,26,22,399.0,1850
21008,Land Rover,Discovery Sport,2017,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,14.982273,20,25,22,406.0,1850
21021,Land Rover,LR2,2015,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,16.480500,17,24,20,450.0,2000
21086,Land Rover,Range Rover Evoque,2014,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.733750,21,30,24,369.0,1700
21087,Land Rover,Range Rover Evoque,2015,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.733750,21,30,24,369.0,1700
21088,Land Rover,Range Rover Evoque,2016,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.733750,21,30,24,369.0,1700
21089,Land Rover,Range Rover Evoque,2017,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,13.733750,21,29,24,372.0,1700
21090,Land Rover,Range Rover Evoque Convertible,2016,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,14.330870,20,28,23,389.0,1750
21091,Land Rover,Range Rover Evoque Convertible,2017,2.0,4.0,Automatic (S9),4-Wheel Drive,Small Sport Utility Vehicle 4WD,Premium,14.330870,20,28,23,391.0,1750

Automatic (variable gear ratios)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
677,Audi,A4,2002,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Premium,15.695714,18,26,21,423.190476,1950
679,Audi,A4,2002,3.0,6.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Premium,17.347895,17,25,19,467.736842,2150
680,Audi,A4,2003,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Premium,14.330870,20,27,23,386.391304,1750
682,Audi,A4,2003,3.0,6.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Premium,15.695714,18,26,21,423.190476,1950
683,Audi,A4,2004,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Premium,14.330870,20,27,23,386.391304,1750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33291,Toyota,Prius v,2013,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,7.847857,44,40,42,211.000000,800
33292,Toyota,Prius v,2014,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,7.847857,44,40,42,211.000000,800
33293,Toyota,Prius v,2015,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,7.847857,44,40,42,211.000000,800
33294,Toyota,Prius v,2016,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,7.847857,44,40,42,211.000000,800
33295,Toyota,Prius v,2017,1.8,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Midsize Station Wagons,Regular,8.039268,43,39,41,217.000000,800

Automatic 3-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
326,Alfa Romeo,Milano,1987,2.5,6.0,Automatic 3-spd,Rear-Wheel Drive,Subcompact Cars,Regular,18.311667,16,21,18,493.722222,1850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35165,Volkswagen,Vanagon/Camper 2WD,1987,2.1,4.0,Automatic 3-spd,Rear-Wheel Drive,Vans,Regular,23.543571,13,15,14,634.785714,2400
35167,Volkswagen,Vanagon/Camper 2WD,1988,2.1,4.0,Automatic 3-spd,Rear-Wheel Drive,Vans,Regular,21.974000,14,16,15,592.466667,2200
35169,Volkswagen,Vanagon/Camper 2WD,1989,2.1,4.0,Automatic 3-spd,Rear-Wheel Drive,Vans,Regular,21.974000,15,16,15,592.466667,2200
35171,Volkswagen,Vanagon/Camper 2WD,1990,2.1,4.0,Automatic 3-spd,Rear-Wheel Drive,Vans,Regular,21.974000,15,16,15,592.466667,2200
35173,Volkswagen,Vanagon/Camper 2WD,1991,2.1,4.0,Automatic 3-spd,Rear-Wheel Drive,Vans,Regular,21.974000,15,16,15,592.466667,2200

Automatic 4-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500
7,Acura,2.2CL/3.0CL,1997,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,18,26,20,444.350000,1650
8,Acura,2.3CL/3.0CL,1998,2.3,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,19,27,22,403.954545,1500
10,Acura,2.3CL/3.0CL,1998,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,17,26,20,444.350000,1650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35916,Wallace Environmental,Wetl 560 SEL,1991,5.6,8.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,25.354615,11,15,13,683.615385,3100
35917,Wallace Environmental,Wetl 560 SEL,1992,5.6,8.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,25.354615,11,15,13,683.615385,3100
35918,Wallace Environmental,Wetl 560 SL,1991,5.6,8.0,Automatic 4-spd,Rear-Wheel Drive,Two Seaters,Premium,25.354615,11,15,13,683.615385,3100
35919,Wallace Environmental,Wetl 600 SEL,1992,6.0,12.0,Automatic 4-spd,Rear-Wheel Drive,Large Cars,Premium,27.467500,11,14,12,740.583333,3400
35920,Wallace Environmental,Wetl 850I,1992,5.0,12.0,Automatic 4-spd,Rear-Wheel Drive,Subcompact Cars,Premium,25.354615,11,17,13,683.615385,3100

Automatic 5-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
26,Acura,3.2TL,2000,3.2,6.0,Automatic 5-spd,Front-Wheel Drive,Midsize Cars,Premium,16.480500,17,27,20,444.350000,2000
119,Acura,MDX,2001,3.5,6.0,Automatic 5-spd,4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,19.388824,15,21,17,522.764706,2400
120,Acura,MDX,2002,3.5,6.0,Automatic 5-spd,4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,19.388824,15,21,17,522.764706,2400
125,Acura,MDX 4WD,2003,3.5,6.0,Automatic 5-spd,4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,19.388824,15,21,17,522.764706,2400
126,Acura,MDX 4WD,2004,3.5,6.0,Automatic 5-spd,4-Wheel or All-Wheel Drive,Sport Utility Vehicle - 4WD,Premium,19.388824,15,21,17,522.764706,2400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35760,Volvo,V70 FWD,2004,2.4,5.0,Automatic 5-spd,Front-Wheel Drive,Midsize Station Wagons,Premium,14.982273,19,28,22,403.954545,1850
35762,Volvo,V70 FWD,2004,2.5,5.0,Automatic 5-spd,Front-Wheel Drive,Midsize Station Wagons,Premium,15.695714,18,26,21,423.190476,1950
35763,Volvo,V70 FWD,2005,2.4,5.0,Automatic 5-spd,Front-Wheel Drive,Midsize Station Wagons,Premium,15.695714,18,26,21,423.190476,1950
35768,Volvo,V70 FWD,2006,2.4,5.0,Automatic 5-spd,Front-Wheel Drive,Midsize Station Wagons,Premium,15.695714,18,26,21,423.190476,1950
35773,Volvo,V70 FWD,2007,2.4,5.0,Automatic 5-spd,Front-Wheel Drive,Midsize Station Wagons,Premium,15.695714,19,27,21,423.190476,1950

Automatic 6-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
322,Alfa Romeo,8 C Spider,2009,4.7,8.0,Automatic 6-spd,Rear-Wheel Drive,Minicompact Cars,Premium,25.354615,11,16,13,683.615385,3100
2474,BMW,745i,2002,4.4,8.0,Automatic 6-spd,Rear-Wheel Drive,Large Cars,Premium,17.347895,16,24,19,467.736842,2150
2475,BMW,745i,2003,4.4,8.0,Automatic 6-spd,Rear-Wheel Drive,Large Cars,Premium,17.347895,16,24,19,467.736842,2150
2478,BMW,745li,2002,4.4,8.0,Automatic 6-spd,Rear-Wheel Drive,Large Cars,Premium,17.347895,16,24,19,467.736842,2150
2479,BMW,745li,2003,4.4,8.0,Automatic 6-spd,Rear-Wheel Drive,Large Cars,Premium,17.347895,16,24,19,467.736842,2150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35076,Volkswagen,Routan,2012,3.6,6.0,Automatic 6-spd,Front-Wheel Drive,Minivan - 2WD,Gasoline or E85,16.480500,17,25,20,444.350000,1650
35077,Volkswagen,Routan,2013,3.6,6.0,Automatic 6-spd,Front-Wheel Drive,Minivan - 2WD,Gasoline or E85,16.480500,17,25,20,453.000000,1650
35078,Volkswagen,Routan,2014,3.6,6.0,Automatic 6-spd,Front-Wheel Drive,Minivan - 2WD,Gasoline or E85,16.480500,17,25,20,455.000000,1650
35079,Volkswagen,Routan FWD,2009,3.8,6.0,Automatic 6-spd,Front-Wheel Drive,Minivan - 2WD,Regular,18.311667,16,23,18,493.722222,1850
35080,Volkswagen,Routan FWD,2009,4.0,6.0,Automatic 6-spd,Front-Wheel Drive,Minivan - 2WD,Regular,16.480500,17,25,20,444.350000,1650

Automatic 6spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
17010,Honda,Accord,2014,3.5,6.0,Automatic 6spd,Front-Wheel Drive,Midsize Cars,Regular,12.677308,21,34,26,346.0,1300

Automatic 7-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
23231,McLaren Automotive,570GT,2017,3.8,8.0,Automatic 7-spd,Rear-Wheel Drive,Two Seaters,Premium,17.347895,16,23,19,481.000000,2150
23232,McLaren Automotive,570S Coupe,2016,3.8,8.0,Automatic 7-spd,Rear-Wheel Drive,Two Seaters,Premium,17.347895,16,23,19,481.000000,2150
23233,McLaren Automotive,570S Coupe,2017,3.8,8.0,Automatic 7-spd,Rear-Wheel Drive,Two Seaters,Premium,17.347895,16,23,19,481.000000,2150
23234,McLaren Automotive,650S Coupe,2015,3.8,8.0,Automatic 7-spd,Rear-Wheel Drive,Two Seaters,Premium,18.311667,16,22,18,499.000000,2250
23235,McLaren Automotive,650S Coupe,2016,3.8,8.0,Automatic 7-spd,Rear-Wheel Drive,Two Seaters,Premium,18.311667,16,22,18,499.000000,2250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29797,Porsche,Panamera Turbo,2011,4.8,8.0,Automatic 7-spd,All-Wheel Drive,Large Cars,Premium,18.311667,15,23,18,493.722222,2250
29798,Porsche,Panamera Turbo,2012,4.8,8.0,Automatic 7-spd,All-Wheel Drive,Large Cars,Premium,18.311667,15,23,18,493.722222,2250
29799,Porsche,Panamera Turbo,2013,4.8,8.0,Automatic 7-spd,All-Wheel Drive,Large Cars,Premium,18.311667,15,23,18,500.000000,2250
29806,Porsche,Panamera Turbo S,2012,4.8,8.0,Automatic 7-spd,All-Wheel Drive,Large Cars,Premium,18.311667,15,23,18,493.722222,2250
29807,Porsche,Panamera Turbo S,2013,4.8,8.0,Automatic 7-spd,All-Wheel Drive,Large Cars,Premium,18.311667,15,23,18,500.000000,2250

Automatic 8-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
2105,BMW,528i,2012,2.0,4.0,Automatic 8-spd,Rear-Wheel Drive,Midsize Cars,Premium,12.207778,23,34,27,329.148148,1500
2119,BMW,528i xDrive,2012,2.0,4.0,Automatic 8-spd,All-Wheel Drive,Midsize Cars,Premium,12.677308,22,32,26,341.807692,1550
3029,BMW,Z4 sDrive28i,2012,2.0,4.0,Automatic 8-spd,Rear-Wheel Drive,Two Seaters,Premium,12.677308,22,32,26,341.807692,1550
3031,BMW,Z4 sDrive28i,2013,2.0,4.0,Automatic 8-spd,Rear-Wheel Drive,Two Seaters,Premium,12.677308,22,33,26,341.000000,1550
4046,Cadillac,Escalade 2WD,2015,6.2,8.0,Automatic 8-spd,Rear-Wheel Drive,Standard Sport Utility Vehicle 2WD,Regular,19.388824,15,22,17,511.000000,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29900,Ram,1500 HFE 2WD,2014,3.6,6.0,Automatic 8-spd,Rear-Wheel Drive,Standard Pickup Trucks 2WD,Regular,15.695714,18,25,21,425.000000,1600
29901,Ram,1500 HFE 2WD,2015,3.6,6.0,Automatic 8-spd,Rear-Wheel Drive,Standard Pickup Trucks 2WD,Regular,15.695714,18,25,21,425.000000,1600
29902,Ram,1500 HFE 2WD,2015,3.0,6.0,Automatic 8-spd,Rear-Wheel Drive,Standard Pickup Trucks 2WD,Diesel,15.924375,21,29,24,425.000000,1500
29903,Ram,1500 HFE 2WD,2016,3.6,6.0,Automatic 8-spd,Rear-Wheel Drive,Standard Pickup Trucks 2WD,Regular,15.695714,18,25,21,425.000000,1600
29904,Ram,1500 HFE 2WD,2016,3.0,6.0,Automatic 8-spd,Rear-Wheel Drive,Standard Pickup Trucks 2WD,Diesel,15.924375,21,29,24,425.000000,1500

Automatic 9-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
6489,Chevrolet,Malibu,2017,2.0,4.0,Automatic 9-spd,Front-Wheel Drive,Midsize Cars,Premium,12.677308,22,33,26,342.0,1550
7930,Chrysler,200,2015,2.4,4.0,Automatic 9-spd,Front-Wheel Drive,Midsize Cars,Regular,11.771786,23,36,28,322.0,1200
7931,Chrysler,200,2015,3.6,6.0,Automatic 9-spd,Front-Wheel Drive,Midsize Cars,Regular,14.330870,19,32,23,385.0,1450
7932,Chrysler,200,2015,2.4,4.0,Automatic 9-spd,Front-Wheel Drive,Midsize Cars,Gasoline or E85,11.771786,23,36,28,322.0,1200
7933,Chrysler,200,2015,3.6,6.0,Automatic 9-spd,Front-Wheel Drive,Midsize Cars,Gasoline or E85,14.330870,19,32,23,385.0,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24441,Mercedes-Benz,SLC300,2017,2.0,4.0,Automatic 9-spd,Rear-Wheel Drive,Two Seaters,Premium,12.207778,25,32,27,324.0,1500
24474,Mercedes-Benz,SLK300,2016,2.0,4.0,Automatic 9-spd,Rear-Wheel Drive,Two Seaters,Premium,11.771786,25,32,28,321.0,1450
29911,Ram,Promaster City,2015,2.4,4.0,Automatic 9-spd,Front-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13.733750,21,29,24,372.0,1400
29912,Ram,Promaster City,2016,2.4,4.0,Automatic 9-spd,Front-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13.733750,21,29,24,372.0,1400
29913,Ram,Promaster City,2017,2.4,4.0,Automatic 9-spd,Front-Wheel Drive,Special Purpose Vehicle 2WD,Regular,13.733750,21,28,24,374.0,1400

Manual 3-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
4580,Chevrolet,C10 Pickup 2WD,1984,4.1,6.0,Manual 3-spd,2-Wheel Drive,Standard Pickup Trucks 2WD,Regular,19.388824,15,19,17,522.764706,1950
4584,Chevrolet,C10 Pickup 2WD,1984,5.0,8.0,Manual 3-spd,2-Wheel Drive,Standard Pickup Trucks 2WD,Regular,21.974000,14,17,15,592.466667,2200
4590,Chevrolet,C10 Pickup 2WD,1984,4.1,6.0,Manual 3-spd,2-Wheel Drive,Standard Pickup Trucks 2WD,Regular,21.974000,14,17,15,592.466667,2200
4596,Chevrolet,C10 Pickup 2WD,1985,4.3,6.0,Manual 3-spd,Rear-Wheel Drive,Standard Pickup Trucks,Regular,20.600625,15,17,16,555.437500,2100
4604,Chevrolet,C10 Pickup 2WD,1985,4.3,6.0,Manual 3-spd,Rear-Wheel Drive,Standard Pickup Trucks,Regular,19.388824,16,19,17,522.764706,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16456,GMC,Vandura G15/25 2WD,1984,4.1,6.0,Manual 3-spd,2-Wheel Drive,"Vans, Cargo Type",Regular,21.974000,14,16,15,592.466667,2200
16462,GMC,Vandura G15/25 2WD,1985,4.3,6.0,Manual 3-spd,Rear-Wheel Drive,Vans,Regular,19.388824,16,19,17,522.764706,1950
16466,GMC,Vandura G15/25 2WD,1985,5.0,8.0,Manual 3-spd,Rear-Wheel Drive,Vans,Regular,23.543571,13,16,14,634.785714,2400
16485,GMC,Vandura G35 2WD,1984,4.1,6.0,Manual 3-spd,2-Wheel Drive,"Vans, Cargo Type",Regular,23.543571,13,15,14,634.785714,2400
16487,GMC,Vandura G35 2WD,1985,4.3,6.0,Manual 3-spd,Rear-Wheel Drive,Vans,Regular,21.974000,14,17,15,592.466667,2200

Manual 4-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
353,American Motors Corporation,Eagle 4WD,1984,2.5,4.0,Manual 4-spd,4-Wheel or All-Wheel Drive,Special Purpose Vehicle 4WD,Regular,16.480500,19,22,20,444.350000,1650
356,American Motors Corporation,Eagle 4WD,1984,4.2,6.0,Manual 4-spd,4-Wheel or All-Wheel Drive,Special Purpose Vehicle 4WD,Regular,19.388824,16,20,17,522.764706,1950
359,American Motors Corporation,Eagle 4WD,1984,4.2,6.0,Manual 4-spd,4-Wheel or All-Wheel Drive,Special Purpose Vehicle 4WD,Regular,19.388824,15,20,17,522.764706,1950
363,American Motors Corporation,Eagle SX/4 4WD,1984,2.5,4.0,Manual 4-spd,4-Wheel or All-Wheel Drive,Special Purpose Vehicle 4WD,Regular,16.480500,19,22,20,444.350000,1650
366,American Motors Corporation,Eagle SX/4 4WD,1984,4.2,6.0,Manual 4-spd,4-Wheel or All-Wheel Drive,Special Purpose Vehicle 4WD,Regular,19.388824,16,20,17,522.764706,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35924,Yugo,GV,1988,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300
35926,Yugo,GV Plus/GV/Cabrio,1990,1.3,4.0,Manual 4-spd,Front-Wheel Drive,Minicompact Cars,Regular,14.330870,21,27,23,386.391304,1450
35928,Yugo,GV/GVX,1987,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300
35929,Yugo,GV/GVX,1989,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,12.677308,24,29,26,341.807692,1300
35931,Yugo,Gy/yugo GVX,1986,1.1,4.0,Manual 4-spd,Front-Wheel Drive,Minicompact Cars,Regular,13.184400,22,29,25,355.480000,1350

Manual 5 spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
35157,Volkswagen,Vanagon Syncro 4WD,1986,2.1,4.0,Manual 5 spd,4-Wheel or All-Wheel Drive,Vans,Regular,23.543571,14,14,14,634.785714,2400

Manual 5-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400
9,Acura,2.3CL/3.0CL,1998,2.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,21,29,24,370.291667,1400
12,Acura,2.3CL/3.0CL,1999,2.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,21,29,24,370.291667,1400
50,Acura,Integra,1986,1.6,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350
52,Acura,Integra,1987,1.6,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35925,Yugo,GV,1988,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,23,27,24,370.291667,1400
35927,Yugo,GV Plus/GV/Cabrio,1990,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350
35930,Yugo,GV/GVX,1989,1.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.184400,23,28,25,355.480000,1350
35939,smart,fortwo cabriolet,2017,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.694412,31,38,34,258.000000,1200
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

Manual 6-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
23,Acura,3.2CL,2003,3.2,6.0,Manual 6-spd,Front-Wheel Drive,Compact Cars,Premium,16.480500,17,26,20,444.350000,2000
40,Acura,ILX,2013,2.4,4.0,Manual 6-spd,Front-Wheel Drive,Compact Cars,Premium,13.184400,22,31,25,361.000000,1600
42,Acura,ILX,2014,2.4,4.0,Manual 6-spd,Front-Wheel Drive,Compact Cars,Premium,13.184400,22,31,25,361.000000,1600
44,Acura,ILX,2015,2.4,4.0,Manual 6-spd,Front-Wheel Drive,Compact Cars,Premium,13.184400,22,31,25,350.000000,1600
108,Acura,Legend,1993,3.2,6.0,Manual 6-spd,Front-Wheel Drive,Compact Cars,Premium,18.311667,15,23,18,493.722222,2250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35781,Volvo,V70 R AWD,2004,2.5,5.0,Manual 6-spd,4-Wheel or All-Wheel Drive,Midsize Station Wagons,Premium,17.347895,16,23,19,467.736842,2150
35783,Volvo,V70 R AWD,2005,2.5,5.0,Manual 6-spd,4-Wheel or All-Wheel Drive,Midsize Station Wagons,Premium,17.347895,16,23,19,467.736842,2150
35785,Volvo,V70 R AWD,2006,2.5,5.0,Manual 6-spd,4-Wheel or All-Wheel Drive,Midsize Station Wagons,Premium,17.347895,16,23,19,467.736842,2150
35787,Volvo,V70 R AWD,2007,2.5,5.0,Manual 6-spd,4-Wheel or All-Wheel Drive,Midsize Station Wagons,Premium,17.347895,16,23,19,467.736842,2150
35921,Wallace Environmental,Wetl 850I,1992,5.0,12.0,Manual 6-spd,Rear-Wheel Drive,Subcompact Cars,Premium,25.354615,10,17,13,683.615385,3100

Manual 7-spd

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
5569,Chevrolet,Corvette,2014,6.2,8.0,Manual 7-spd,Rear-Wheel Drive,Two Seaters,Premium,15.695714,17,29,21,424.000000,1950
5571,Chevrolet,Corvette,2015,6.2,8.0,Manual 7-spd,Rear-Wheel Drive,Two Seaters,Premium,15.695714,17,29,21,424.000000,1950
5574,Chevrolet,Corvette,2015,6.2,8.0,Manual 7-spd,Rear-Wheel Drive,Two Seaters,Premium,18.311667,15,22,18,503.000000,2250
5580,Chevrolet,Corvette,2017,6.2,8.0,Manual 7-spd,Rear-Wheel Drive,Two Seaters,Premium,17.347895,16,25,19,465.000000,2150
5581,Chevrolet,Corvette,2017,6.2,8.0,Manual 7-spd,Rear-Wheel Drive,Two Seaters,Premium,18.311667,15,22,18,503.000000,2250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29264,Porsche,911 Targa 4S,2017,3.0,6.0,Manual 7-spd,4-Wheel Drive,Minicompact Cars,Premium,14.982273,19,28,22,396.000000,1850
29750,Porsche,New 911 Carrera,2012,3.4,6.0,Manual 7-spd,Rear-Wheel Drive,Minicompact Cars,Premium,14.982273,19,27,22,403.954545,1850
29752,Porsche,New 911 Carrera Cabriolet,2012,3.4,6.0,Manual 7-spd,Rear-Wheel Drive,Minicompact Cars,Premium,14.982273,19,27,22,403.954545,1850
29754,Porsche,New 911 Carrera S,2012,3.8,6.0,Manual 7-spd,Rear-Wheel Drive,Minicompact Cars,Premium,14.982273,19,27,22,403.954545,1850
29756,Porsche,New 911 Carrera S Cabriolet,2012,3.8,6.0,Manual 7-spd,Rear-Wheel Drive,Minicompact Cars,Premium,14.982273,19,27,22,403.954545,1850

Manual(M7)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
453,Aston Martin,V12 Vantage S,2017,6.0,12.0,Manual(M7),Rear-Wheel Drive,Two Seaters,Premium,27.467500,10,16,12,724.0,3400
5576,Chevrolet,Corvette,2016,6.2,8.0,Manual(M7),Rear-Wheel Drive,Two Seaters,Premium,18.311667,15,22,18,491.0,2250
5578,Chevrolet,Corvette,2016,6.2,8.0,Manual(M7),Rear-Wheel Drive,Two Seaters,Premium,15.695714,17,29,21,424.0,1950

In [12]:
df.groupby('Transmission')[['Highway MPG','City MPG','Combined MPG']].mean()

                                  Highway MPG   City MPG  Combined MPG
Transmission
Auto (AV)                           40.000000  35.000000     37.000000
Auto (AV-S6)                        25.000000  22.000000     23.000000
Auto (AV-S8)                        22.000000  20.000000     21.000000
Auto(A1)                            37.000000  41.000000     39.000000
Auto(AM-S6)                         32.978261  24.315217     27.554348
Auto(AM-S7)                         25.300781  17.746094     20.425781
Auto(AM-S8)                         32.000000  23.666667     26.666667
Auto(AM-S9)                         22.000000  21.000000     21.000000
Auto(AM5)                           39.000000  33.666667     36.000000
Auto(AM6)                           31.345455  23.909091     26.736364
Auto(AM7)                           22.382166  16.248408     18.420382
Auto(AM8)                           28.600000  22.400000     24.600000
Auto(AV-S6)                         30.800000  25.944828     27.848276
Auto(AV-S7)                         33.746032  27.952381     30.206349
Auto(AV-S8)                         28.538462  22.846154     24.961538
Auto(L3)                            17.000000  14.000000     15.500000
Auto(L4)                            19.000000  13.500000     15.500000
Automatic (A1)                      31.666667  34.000000     32.666667
Automatic (A6)                      21.000000  14.000000     16.500000
Automatic (AM5)                     41.000000  33.000000     36.000000
Automatic (AM6)                     18.000000  13.000000     15.000000
Automatic (AV)                      30.000000  21.750000     24.750000
Automatic (AV-S6)                   27.777778  23.666667     25.222222
Automatic (S4)                      24.768559  18.074236     20.528384
Automatic (S5)                      24.205596  17.087591     19.698297
Automatic (S6)                      25.938807  18.337514     21.096921
Automatic (S7)                      23.605364  16.804598     19.195402
Automatic (S8)                      26.983333  18.450000     21.500000
Automatic (S9)                      28.307692  19.923077     23.038462
Automatic (variable gear ratios)    31.094815  27.460741     28.777778
Automatic 3-spd                     21.630343  17.449750     19.033500
Automatic 4-spd                     21.691639  15.944261     18.042607
Automatic 5-spd                     21.647167  15.445417     17.693229
Automatic 6-spd                     23.768156  16.720670     19.237430
Automatic 6spd                      34.000000  21.000000     26.000000
Automatic 7-spd                     24.413897  17.117825     19.746224
Automatic 8-spd                     24.448560  16.576132     19.279835
Automatic 9-spd                     28.366667  20.077778     23.200000
Manual 3-spd                        16.945946  14.229730     15.256757
Manual 4-spd                        21.042113  16.871363     18.462481
Manual 5 spd                        14.000000  14.000000     14.000000
Manual 5-spd                        25.664312  19.242327     21.634391
Manual 6-spd                        26.202229  18.306232     21.153941
Manual 7-spd                        26.205882  18.220588     21.117647
Manual(M7)                          22.333333  14.000000     17.000000

In [13]:
df.groupby('Transmission')[['Highway MPG','City MPG','Combined MPG']].agg('mean')

                                  Highway MPG   City MPG  Combined MPG
Transmission
Auto (AV)                           40.000000  35.000000     37.000000
Auto (AV-S6)                        25.000000  22.000000     23.000000
Auto (AV-S8)                        22.000000  20.000000     21.000000
Auto(A1)                            37.000000  41.000000     39.000000
Auto(AM-S6)                         32.978261  24.315217     27.554348
Auto(AM-S7)                         25.300781  17.746094     20.425781
Auto(AM-S8)                         32.000000  23.666667     26.666667
Auto(AM-S9)                         22.000000  21.000000     21.000000
Auto(AM5)                           39.000000  33.666667     36.000000
Auto(AM6)                           31.345455  23.909091     26.736364
Auto(AM7)                           22.382166  16.248408     18.420382
Auto(AM8)                           28.600000  22.400000     24.600000
Auto(AV-S6)                         30.800000  25.944828     27.848276
Auto(AV-S7)                         33.746032  27.952381     30.206349
Auto(AV-S8)                         28.538462  22.846154     24.961538
Auto(L3)                            17.000000  14.000000     15.500000
Auto(L4)                            19.000000  13.500000     15.500000
Automatic (A1)                      31.666667  34.000000     32.666667
Automatic (A6)                      21.000000  14.000000     16.500000
Automatic (AM5)                     41.000000  33.000000     36.000000
Automatic (AM6)                     18.000000  13.000000     15.000000
Automatic (AV)                      30.000000  21.750000     24.750000
Automatic (AV-S6)                   27.777778  23.666667     25.222222
Automatic (S4)                      24.768559  18.074236     20.528384
Automatic (S5)                      24.205596  17.087591     19.698297
Automatic (S6)                      25.938807  18.337514     21.096921
Automatic (S7)                      23.605364  16.804598     19.195402
Automatic (S8)                      26.983333  18.450000     21.500000
Automatic (S9)                      28.307692  19.923077     23.038462
Automatic (variable gear ratios)    31.094815  27.460741     28.777778
Automatic 3-spd                     21.630343  17.449750     19.033500
Automatic 4-spd                     21.691639  15.944261     18.042607
Automatic 5-spd                     21.647167  15.445417     17.693229
Automatic 6-spd                     23.768156  16.720670     19.237430
Automatic 6spd                      34.000000  21.000000     26.000000
Automatic 7-spd                     24.413897  17.117825     19.746224
Automatic 8-spd                     24.448560  16.576132     19.279835
Automatic 9-spd                     28.366667  20.077778     23.200000
Manual 3-spd                        16.945946  14.229730     15.256757
Manual 4-spd                        21.042113  16.871363     18.462481
Manual 5 spd                        14.000000  14.000000     14.000000
Manual 5-spd                        25.664312  19.242327     21.634391
Manual 6-spd                        26.202229  18.306232     21.153941
Manual 7-spd                        26.205882  18.220588     21.117647
Manual(M7)                          22.333333  14.000000     17.000000

In [16]:
df.groupby('Transmission')[['Highway MPG','City MPG','Combined MPG']].apply(np.mean)

                                  Highway MPG   City MPG  Combined MPG
Transmission
Auto (AV)                           40.000000  35.000000     37.000000
Auto (AV-S6)                        25.000000  22.000000     23.000000
Auto (AV-S8)                        22.000000  20.000000     21.000000
Auto(A1)                            37.000000  41.000000     39.000000
Auto(AM-S6)                         32.978261  24.315217     27.554348
Auto(AM-S7)                         25.300781  17.746094     20.425781
Auto(AM-S8)                         32.000000  23.666667     26.666667
Auto(AM-S9)                         22.000000  21.000000     21.000000
Auto(AM5)                           39.000000  33.666667     36.000000
Auto(AM6)                           31.345455  23.909091     26.736364
Auto(AM7)                           22.382166  16.248408     18.420382
Auto(AM8)                           28.600000  22.400000     24.600000
Auto(AV-S6)                         30.800000  25.944828     27.848276
Auto(AV-S7)                         33.746032  27.952381     30.206349
Auto(AV-S8)                         28.538462  22.846154     24.961538
Auto(L3)                            17.000000  14.000000     15.500000
Auto(L4)                            19.000000  13.500000     15.500000
Automatic (A1)                      31.666667  34.000000     32.666667
Automatic (A6)                      21.000000  14.000000     16.500000
Automatic (AM5)                     41.000000  33.000000     36.000000
Automatic (AM6)                     18.000000  13.000000     15.000000
Automatic (AV)                      30.000000  21.750000     24.750000
Automatic (AV-S6)                   27.777778  23.666667     25.222222
Automatic (S4)                      24.768559  18.074236     20.528384
Automatic (S5)                      24.205596  17.087591     19.698297
Automatic (S6)                      25.938807  18.337514     21.096921
Automatic (S7)                      23.605364  16.804598     19.195402
Automatic (S8)                      26.983333  18.450000     21.500000
Automatic (S9)                      28.307692  19.923077     23.038462
Automatic (variable gear ratios)    31.094815  27.460741     28.777778
Automatic 3-spd                     21.630343  17.449750     19.033500
Automatic 4-spd                     21.691639  15.944261     18.042607
Automatic 5-spd                     21.647167  15.445417     17.693229
Automatic 6-spd                     23.768156  16.720670     19.237430
Automatic 6spd                      34.000000  21.000000     26.000000
Automatic 7-spd                     24.413897  17.117825     19.746224
Automatic 8-spd                     24.448560  16.576132     19.279835
Automatic 9-spd                     28.366667  20.077778     23.200000
Manual 3-spd                        16.945946  14.229730     15.256757
Manual 4-spd                        21.042113  16.871363     18.462481
Manual 5 spd                        14.000000  14.000000     14.000000
Manual 5-spd                        25.664312  19.242327     21.634391
Manual 6-spd                        26.202229  18.306232     21.153941
Manual 7-spd                        26.205882  18.220588     21.117647
Manual(M7)                          22.333333  14.000000     17.000000

In [21]:
df.groupby(['Fuel Type','Cylinders'])['CO2 Emission Grams/Mile'].agg('median').sort_values(ascending=False)

Fuel Type                    Cylinders
Premium                      16.0         888.700000
Regular                      10.0         776.500000
Gasoline or natural gas      8.0          740.583333
Regular                      12.0         683.615385
Premium                      12.0         683.615385
Gasoline or propane          8.0          666.525000
Premium                      10.0         634.785714
Regular                      8.0          634.785714
Premium or E85               12.0         633.892857
Diesel                       8.0          598.823529
                             10.0         598.823529
Gasoline or E85              8.0          592.466667
CNG                          8.0          568.070913
Midgrade                     8.0          527.000000
Premium                      8.0          522.764706
Regular                      2.0          522.764706
Premium or E85               8.0          504.000000
Regular                      6.0          493.722222
Premium                      2.0          493.722222
Regular                      5.0          467.736842
Premium and Electricity      8.0          463.000000
Premium                      6.0          444.350000
Gasoline or E85              6.0          444.350000
Premium                      5.0          444.350000
Diesel                       6.0          439.000000
Gasoline or natural gas      6.0          437.000000
Premium or E85               6.0          423.190476
CNG                          6.0          417.030882
Midgrade                     6.0          416.000000
Diesel                       5.0          391.538462
Premium                      4.0          386.391304
Regular                      4.0          386.391304
Gasoline or natural gas      4.0          386.391304
Premium or E85               4.0          373.000000
Gasoline or E85              4.0          355.480000
Diesel                       4.0          308.484848
Premium Gas or Electricity   8.0          277.000000
                             6.0          260.000000
CNG                          4.0          253.197321
Regular                      3.0          247.000000
Premium                      3.0          246.861111
Premium and Electricity      6.0          228.000000
                             4.0          214.000000
                             3.0          198.000000
Regular Gas and Electricity  4.0          129.000000
Premium Gas or Electricity   4.0           89.000000
Regular Gas or Electricity   4.0           51.000000
Premium Gas or Electricity   2.0           40.000000
Name: CO2 Emission Grams/Mile, dtype: float64

In [22]:
df.groupby('Fuel Type')['Combined MPG'].agg(['median','mean','std','max','min','count'])

                             median       mean       std  max  min  count
Fuel Type
CNG                            14.5  18.133333  7.436663   31    9     60
Diesel                         21.0  23.488474  7.054702   40   14    911
Gasoline or E85                17.0  17.572385  3.822538   33   11   1195
Gasoline or natural gas        12.0  15.350000  5.343712   24   10     20
Gasoline or propane            13.5  13.500000  1.603567   15   12      8
Midgrade                       17.0  17.378378  1.848381   24   15     74
Premium                        19.0  19.343816  4.097972   45    7   9921
Premium Gas or Electricity     33.0  31.647059  7.158397   39   20     17
Premium and Electricity        25.5  26.300000  5.141165   39   17     20
Premium or E85                 20.0  20.090909  3.676502   27   13    121
Regular                        20.0  20.144698  5.317500   56    8  23587
Regular Gas and Electricity    38.5  41.937500  5.246824   50   38     16
Regular Gas or Electricity     42.0  42.000000  0.000000   42   42      2

In [23]:
df.groupby('Fuel Type')['Combined MPG'].agg('describe')

,count,mean,std,min,25%,50%,75%,max
Fuel Type,,,,,,,,
CNG,60.0,18.133333,7.436663,9.0,12.00,14.5,27.25,31.0
Diesel,911.0,23.488474,7.054702,14.0,17.00,21.0,29.00,40.0
Gasoline or E85,1195.0,17.572385,3.822538,11.0,14.00,17.0,20.00,33.0
Gasoline or natural gas,20.0,15.350000,5.343712,10.0,11.75,12.0,20.50,24.0
Gasoline or propane,8.0,13.500000,1.603567,12.0,12.00,13.5,15.00,15.0
Midgrade,74.0,17.378378,1.848381,15.0,16.00,17.0,19.00,24.0
Premium,9921.0,19.343816,4.097972,7.0,17.00,19.0,21.00,45.0
Premium Gas or Electricity,17.0,31.647059,7.158397,20.0,22.00,33.0,37.00,39.0
Premium and Electricity,20.0,26.300000,5.141165,17.0,24.75,25.5,28.00,39.0
Premium or E85,121.0,20.090909,3.676502,13.0,18.00,20.0,23.00,27.0
Regular,23587.0,20.144698,5.317500,8.0,16.00,20.0,23.00,56.0
Regular Gas and Electricity,16.0,41.937500,5.246824,38.0,38.00,38.5,47.00,50.0
Regular Gas or Electricity,2.0,42.000000,0.000000,42.0,42.00,42.0,42.00,42.0

In [24]:
df.groupby('Fuel Type')[['Combined MPG','Highway MPG']].agg({'Combined MPG':'mean','Highway MPG':['median','std']})

                            Combined MPG Highway MPG
                                    mean      median       std
Fuel Type
CNG                            18.133333        18.5  9.058177
Diesel                         23.488474        24.0  8.660046
Gasoline or E85                17.572385        20.0  5.007313
Gasoline or natural gas        15.350000        15.0  6.522027
Gasoline or propane            13.500000        16.5  1.603567
Midgrade                       17.378378        22.0  2.373220
Premium                        19.343816        24.0  4.728452
Premium Gas or Electricity     31.647059        35.0  6.930326
Premium and Electricity        26.300000        29.0  5.240530
Premium or E85                 20.090909        25.0  4.006245
Regular                        20.144698        24.0  6.147280
Regular Gas and Electricity    41.937500        38.0  5.662744
Regular Gas or Electricity     42.000000        42.0  0.000000

In [27]:
df.groupby('Fuel Type').agg('mean')

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
Fuel Type,,,,,,,,,
CNG,2003.200000,3.963333,6.500000,0.119789,15.966667,22.016667,18.133333,454.976354,1954.166667
Diesel,1994.929748,4.188913,6.225027,17.680877,21.173436,27.466520,23.488474,470.905819,1673.326015
Gasoline or E85,2010.501255,4.465188,6.974059,19.560309,15.347280,21.613389,17.572385,527.444383,1978.870293
Gasoline or natural gas,2004.000000,4.570000,6.800000,23.725940,13.700000,18.700000,15.350000,638.967778,2410.000000
Gasoline or propane,2002.500000,5.400000,8.000000,24.720750,12.000000,16.500000,13.500000,666.525000,2500.000000
Midgrade,2014.148649,5.536486,7.864865,19.163168,14.851351,22.364865,17.378378,516.911921,2152.027027
Premium,2005.575345,3.517075,6.365286,17.852563,16.793166,23.855861,19.343816,481.159270,2198.094950
Premium Gas or Electricity,2014.470588,1.764706,4.235294,4.755412,30.705882,33.176471,31.647059,125.411765,1361.764706
Premium and Electricity,2015.700000,2.345000,4.850000,8.135294,24.900000,28.900000,26.300000,239.450000,1597.500000
Premium or E85,2012.917355,3.680992,6.892562,17.021126,17.305785,24.909091,20.090909,460.462355,2091.322314
Regular,1998.252597,3.164540,5.420952,17.467430,17.970195,23.854623,20.144698,470.907242,1767.024208
Regular Gas and Electricity,2014.625000,1.950000,4.000000,4.669536,43.125000,40.750000,41.937500,125.687500,812.500000
Regular Gas or Electricity,2016.500000,1.500000,4.000000,2.006844,43.000000,42.000000,42.000000,51.000000,800.000000

# Pivot

In [31]:
df.pivot_table(index='Vehicle Class',columns='Cylinders')

                                   CO2 Emission Grams/Mile              \
Cylinders                                             2.0         3.0
Vehicle Class
Compact Cars                                           NaN  243.666667
Large Cars                                             NaN         NaN
Midsize Cars                                           NaN         NaN
Midsize Station Wagons                                 NaN         NaN
Midsize-Large Station Wagons                           NaN         NaN
Minicompact Cars                                493.722222  234.692515
Minivan - 2WD                                          NaN         NaN
Minivan - 4WD                                          NaN         NaN
Small Pickup Trucks                                    NaN         NaN
Small Pickup Trucks 2WD                                NaN         NaN
Small Pickup Trucks 4WD                                NaN         NaN
Small Sport Utility Vehicle 2WD                        NaN         NaN
Small Sport Utility Vehicle 4WD                        NaN         NaN
Small Station Wagons                                   NaN         NaN
Special Purpose Vehicle                                NaN         NaN
Special Purpose Vehicle 2WD                            NaN         NaN
Special Purpose Vehicle 4WD                            NaN         NaN
Special Purpose Vehicles                               NaN  317.392857
Special Purpose Vehicles/2wd                           NaN         NaN
Special Purpose Vehicles/4wd                           NaN         NaN
Sport Utility Vehicle - 2WD                            NaN         NaN
Sport Utility Vehicle - 4WD                            NaN         NaN
Standard Pickup Trucks                                 NaN         NaN
Standard Pickup Trucks 2WD                             NaN         NaN
Standard Pickup Trucks 4WD                             NaN         NaN
Standard Pickup Trucks/2wd                             NaN         NaN
Standard Sport Utility Vehicle 2WD                     NaN         NaN
Standard Sport Utility Vehicle 4WD                     NaN         NaN
Subcompact Cars                                 413.718067  253.757448
Two Seaters                                     510.317927  229.371716
Vans                                                   NaN         NaN
Vans Passenger                                         NaN         NaN
Vans, Cargo Type                                       NaN         NaN
Vans, Passenger Type                                   NaN         NaN

                                                                        \
Cylinders                                 4.0         5.0         6.0
Vehicle Class
Compact Cars                        359.664477  410.342455  448.236147
Large Cars                          378.225886         NaN  439.084500
Midsize Cars                        358.033422  455.120960  443.496348
Midsize Station Wagons              388.835273  440.555715  455.490145
Midsize-Large Station Wagons        433.088892  473.112667  464.888691
Minicompact Cars                    363.662177  394.197189  462.328742
Minivan - 2WD                       421.127016         NaN  474.621148
Minivan - 4WD                              NaN         NaN  504.595699
Small Pickup Trucks                 426.596408         NaN  498.855555
Small Pickup Trucks 2WD             421.974518  494.161681  499.879463
Small Pickup Trucks 4WD             460.204965  494.412536  525.708494
Small Sport Utility Vehicle 2WD     357.035857         NaN  420.886179
Small Sport Utility Vehicle 4WD     371.414286  404.250000  445.067308
Small Station Wagons                362.064456  407.326178  456.330551
Special Purpose Vehicle             462.727273         NaN         NaN
Special Purpose Vehicle 2WD         446.318168         NaN  541.214769
Special Purpose Vehicle 4WD         446.957113         NaN  550.752521
Special Purpose Vehicles            453.016883         NaN  560.834862
Special Purpose Vehicles/2wd        423.190476         NaN  493.722222
Special Purpose Vehicles/4wd               NaN         NaN  522.764706
Sport Utility Vehicle - 2WD         398.989398  488.525146  494.964096
Sport Utility Vehicle - 4WD         420.998147  526.000719  516.446173
Standard Pickup Trucks              468.421444         NaN  561.941022
Standard Pickup Trucks 2WD          438.812497  493.047112  529.386185
Standard Pickup Trucks 4WD          495.638122  515.984305  564.258967
Standard Pickup Trucks/2wd                 NaN         NaN         NaN
Standard Sport Utility Vehicle 2WD  367.846154         NaN  460.848101
Standard Sport Utility Vehicle 4WD  352.421053         NaN  456.910995
Subcompact Cars                     365.346610  436.478241  448.852081
Two Seaters                         368.032758         NaN  456.994452
Vans                                483.864645  563.061152  572.256677
Vans Passenger                             NaN         NaN  522.764706
Vans, Cargo Type                    410.180159         NaN  590.174119
Vans, Passenger Type                503.861161  592.466667  603.095090

                                                                        \
Cylinders                                 8.0         10.0        12.0
Vehicle Class
Compact Cars                        550.880512         NaN  648.289761
Large Cars                          522.153991         NaN  645.151820
Midsize Cars                        545.353319  629.830939  687.734218
Midsize Station Wagons              539.650696         NaN         NaN
Midsize-Large Station Wagons        505.575496         NaN         NaN
Minicompact Cars                    538.091605         NaN  679.324024
Minivan - 2WD                              NaN         NaN         NaN
Minivan - 4WD                              NaN         NaN         NaN
Small Pickup Trucks                        NaN         NaN         NaN
Small Pickup Trucks 2WD             539.101103         NaN         NaN
Small Pickup Trucks 4WD             555.437500         NaN         NaN
Small Sport Utility Vehicle 2WD            NaN         NaN         NaN
Small Sport Utility Vehicle 4WD     549.000000         NaN         NaN
Small Station Wagons                561.226475         NaN         NaN
Special Purpose Vehicle                    NaN         NaN         NaN
Special Purpose Vehicle 2WD         659.251422         NaN         NaN
Special Purpose Vehicle 4WD         689.650798         NaN         NaN
Special Purpose Vehicles            699.146875         NaN         NaN
Special Purpose Vehicles/2wd               NaN         NaN         NaN
Special Purpose Vehicles/4wd               NaN         NaN         NaN
Sport Utility Vehicle - 2WD         586.984933         NaN         NaN
Sport Utility Vehicle - 4WD         622.036464  590.506536         NaN
Standard Pickup Trucks              669.517382         NaN         NaN
Standard Pickup Trucks 2WD          594.703656  928.197778         NaN
Standard Pickup Trucks 4WD          621.707831         NaN         NaN
Standard Pickup Trucks/2wd          687.684524         NaN         NaN
Standard Sport Utility Vehicle 2WD  529.390805         NaN         NaN
Standard Sport Utility Vehicle 4WD  564.974619         NaN  679.000000
Subcompact Cars                     554.586999  683.615385  684.097974
Two Seaters                         569.191132  629.643589  769.237529
Vans                                684.058384         NaN         NaN
Vans Passenger                      740.583333         NaN         NaN
Vans, Cargo Type                    642.127632  751.791667         NaN
Vans, Passenger Type                665.697909  801.704545         NaN

                                               City MPG  ... Highway MPG  \
Cylinders                               16.0       2.0   ...        16.0
Vehicle Class                                            ...
Compact Cars                             NaN        NaN  ...         NaN
Large Cars                               NaN        NaN  ...         NaN
Midsize Cars                             NaN        NaN  ...         NaN
Midsize Station Wagons                   NaN        NaN  ...         NaN
Midsize-Large Station Wagons             NaN        NaN  ...         NaN
Minicompact Cars                         NaN  15.000000  ...         NaN
Minivan - 2WD                            NaN        NaN  ...         NaN
Minivan - 4WD                            NaN        NaN  ...         NaN
Small Pickup Trucks                      NaN        NaN  ...         NaN
Small Pickup Trucks 2WD                  NaN        NaN  ...         NaN
Small Pickup Trucks 4WD                  NaN        NaN  ...         NaN
Small Sport Utility Vehicle 2WD          NaN        NaN  ...         NaN
Small Sport Utility Vehicle 4WD          NaN        NaN  ...         NaN
Small Station Wagons                     NaN        NaN  ...         NaN
Special Purpose Vehicle                  NaN        NaN  ...         NaN
Special Purpose Vehicle 2WD              NaN        NaN  ...         NaN
Special Purpose Vehicle 4WD              NaN        NaN  ...         NaN
Special Purpose Vehicles                 NaN        NaN  ...         NaN
Special Purpose Vehicles/2wd             NaN        NaN  ...         NaN
Special Purpose Vehicles/4wd             NaN        NaN  ...         NaN
Sport Utility Vehicle - 2WD              NaN        NaN  ...         NaN
Sport Utility Vehicle - 4WD              NaN        NaN  ...         NaN
Standard Pickup Trucks                   NaN        NaN  ...         NaN
Standard Pickup Trucks 2WD               NaN        NaN  ...         NaN
Standard Pickup Trucks 4WD               NaN        NaN  ...         NaN
Standard Pickup Trucks/2wd               NaN        NaN  ...         NaN
Standard Sport Utility Vehicle 2WD       NaN        NaN  ...         NaN
Standard Sport Utility Vehicle 4WD       NaN        NaN  ...         NaN
Subcompact Cars                          NaN  19.947368  ...         NaN
Two Seaters                         873.0625  15.071429  ...      14.625
Vans                                     NaN        NaN  ...         NaN
Vans Passenger                           NaN        NaN  ...         NaN
Vans, Cargo Type                         NaN        NaN  ...         NaN
Vans, Passenger Type                     NaN        NaN  ...         NaN

                                           Year                            \
Cylinders                                  2.0          3.0          4.0
Vehicle Class
Compact Cars                                NaN  2015.666667  2000.506620
Large Cars                                  NaN          NaN  2005.731034
Midsize Cars                                NaN          NaN  2003.884058
Midsize Station Wagons                      NaN          NaN  2004.369427
Midsize-Large Station Wagons                NaN          NaN  1990.330303
Minicompact Cars                    1986.000000  1986.315789  2002.493438
Minivan - 2WD                               NaN          NaN  2006.757576
Minivan - 4WD                               NaN          NaN          NaN
Small Pickup Trucks                         NaN          NaN  1988.449153
Small Pickup Trucks 2WD                     NaN          NaN  1999.212500
Small Pickup Trucks 4WD                     NaN          NaN  1999.564103
Small Sport Utility Vehicle 2WD             NaN          NaN  2015.023904
Small Sport Utility Vehicle 4WD             NaN          NaN  2015.139286
Small Station Wagons                        NaN          NaN  2000.394340
Special Purpose Vehicle                     NaN          NaN  2003.000000
Special Purpose Vehicle 2WD                 NaN          NaN  1993.329218
Special Purpose Vehicle 4WD                 NaN          NaN  1989.266667
Special Purpose Vehicles                    NaN  1988.000000  1990.915612
Special Purpose Vehicles/2wd                NaN          NaN  1997.000000
Special Purpose Vehicles/4wd                NaN          NaN          NaN
Sport Utility Vehicle - 2WD                 NaN          NaN  2006.487280
Sport Utility Vehicle - 4WD                 NaN          NaN  2006.000000
Standard Pickup Trucks                      NaN          NaN  1990.403636
Standard Pickup Trucks 2WD                  NaN          NaN  2001.683099
Standard Pickup Trucks 4WD                  NaN          NaN  2001.357143
Standard Pickup Trucks/2wd                  NaN          NaN          NaN
Standard Sport Utility Vehicle 2WD          NaN          NaN  2015.307692
Standard Sport Utility Vehicle 4WD          NaN          NaN  2015.894737
Subcompact Cars                     2008.684211  1993.234375  1995.866475
Two Seaters                         1989.571429  2005.463415  2000.870044
Vans                                        NaN          NaN  1988.193103
Vans Passenger                              NaN          NaN          NaN
Vans, Cargo Type                            NaN          NaN  1993.666667
Vans, Passenger Type                        NaN          NaN  1984.000000

                                                                           \
Cylinders                                  5.0          6.0          8.0
Vehicle Class
Compact Cars                        2004.829384  2000.492887  2005.281879
Large Cars                                  NaN  2004.765101  2003.966387
Midsize Cars                        1994.795181  2001.656977  2001.524812
Midsize Station Wagons              2002.770270  2004.042945  2007.227273
Midsize-Large Station Wagons        1990.545455  1989.578431  1988.818182
Minicompact Cars                    2007.777778  2006.248826  2003.842593
Minivan - 2WD                               NaN  2006.338926          NaN
Minivan - 4WD                               NaN  2005.063830          NaN
Small Pickup Trucks                         NaN  1989.958824          NaN
Small Pickup Trucks 2WD             2009.875000  2003.150442  2010.500000
Small Pickup Trucks 4WD             2009.935484  2007.013333  2010.500000
Small Sport Utility Vehicle 2WD             NaN  2014.634146          NaN
Small Sport Utility Vehicle 4WD     2015.500000  2014.769231  2013.500000
Small Station Wagons                2005.234375  2002.868778  2005.692308
Special Purpose Vehicle                     NaN          NaN          NaN
Special Purpose Vehicle 2WD                 NaN  1991.558952  1991.880734
Special Purpose Vehicle 4WD                 NaN  1992.346154  1991.129870
Special Purpose Vehicles                    NaN  1992.526570  1991.224026
Special Purpose Vehicles/2wd                NaN  1997.000000          NaN
Special Purpose Vehicles/4wd                NaN  1997.000000          NaN
Sport Utility Vehicle - 2WD         2005.000000  2006.079942  2006.299270
Sport Utility Vehicle - 4WD         2006.045455  2006.331627  2006.318182
Standard Pickup Trucks                      NaN  1990.662804  1990.390452
Standard Pickup Trucks 2WD          2005.666667  2002.767677  2003.498239
Standard Pickup Trucks 4WD          2006.100000  2002.983146  2004.632495
Standard Pickup Trucks/2wd                  NaN          NaN  1995.000000
Standard Sport Utility Vehicle 2WD          NaN  2015.139241  2014.770115
Standard Sport Utility Vehicle 4WD          NaN  2014.979058  2014.807107
Subcompact Cars                     1998.534091  2001.820342  2002.408056
Two Seaters                                 NaN  2004.393939  2005.148325
Vans                                1994.000000  1989.873494  1989.951271
Vans Passenger                              NaN  1990.000000  1995.000000
Vans, Cargo Type                            NaN  1998.368056  2003.551601
Vans, Passenger Type                1993.000000  1999.493827  2004.270142


Cylinders                                  10.0         12.0      16.0
Vehicle Class
Compact Cars                                NaN  2008.557143       NaN
Large Cars                                  NaN  2008.224638       NaN
Midsize Cars                        2008.411765  2007.250000       NaN
Midsize Station Wagons                      NaN          NaN       NaN
Midsize-Large Station Wagons                NaN          NaN       NaN
Minicompact Cars                            NaN  2008.290909       NaN
Minivan - 2WD                               NaN          NaN       NaN
Minivan - 4WD                               NaN          NaN       NaN
Small Pickup Trucks                         NaN          NaN       NaN
Small Pickup Trucks 2WD                     NaN          NaN       NaN
Small Pickup Trucks 4WD                     NaN          NaN       NaN
Small Sport Utility Vehicle 2WD             NaN          NaN       NaN
Small Sport Utility Vehicle 4WD             NaN          NaN       NaN
Small Station Wagons                        NaN          NaN       NaN
Special Purpose Vehicle                     NaN          NaN       NaN
Special Purpose Vehicle 2WD                 NaN          NaN       NaN
Special Purpose Vehicle 4WD                 NaN          NaN       NaN
Special Purpose Vehicles                    NaN          NaN       NaN
Special Purpose Vehicles/2wd                NaN          NaN       NaN
Special Purpose Vehicles/4wd                NaN          NaN       NaN
Sport Utility Vehicle - 2WD                 NaN          NaN       NaN
Sport Utility Vehicle - 4WD         2006.250000          NaN       NaN
Standard Pickup Trucks                      NaN          NaN       NaN
Standard Pickup Trucks 2WD          2005.200000          NaN       NaN
Standard Pickup Trucks 4WD                  NaN          NaN       NaN
Standard Pickup Trucks/2wd                  NaN          NaN       NaN
Standard Sport Utility Vehicle 2WD          NaN          NaN       NaN
Standard Sport Utility Vehicle 4WD          NaN  2016.500000       NaN
Subcompact Cars                     2008.352941  2001.446154       NaN
Two Seaters                         2008.892157  2004.319767  2011.125
Vans                                        NaN          NaN       NaN
Vans Passenger                              NaN          NaN       NaN
Vans, Cargo Type                    2012.500000          NaN       NaN
Vans, Passenger Type                2012.500000          NaN       NaN

[34 rows x 72 columns]

In [32]:
df.pivot_table(index='Vehicle Class',columns='Cylinders', values='Combined MPG')

Cylinders,2.0,3.0,4.0,5.0,6.0,8.0,10.0,12.0,16.0
Vehicle Class,,,,,,,,,
Compact Cars,NaN,36.333333,25.381877,21.943128,20.051046,16.536913,NaN,13.757143,NaN
Large Cars,NaN,NaN,24.275862,NaN,20.379866,17.323529,NaN,13.884058,NaN
Midsize Cars,NaN,NaN,25.830698,19.710843,20.336047,16.837594,14.235294,13.050000,NaN
Midsize Station Wagons,NaN,NaN,23.515924,20.229730,19.582822,16.590909,NaN,NaN,NaN
Midsize-Large Station Wagons,NaN,NaN,20.769697,19.030303,19.397059,17.772727,NaN,NaN,NaN
Minicompact Cars,18.000000,38.421053,25.078740,22.555556,19.464789,16.824074,NaN,13.181818,NaN
Minivan - 2WD,NaN,NaN,21.515152,NaN,18.852349,NaN,NaN,NaN,NaN
Minivan - 4WD,NaN,NaN,NaN,NaN,17.638298,NaN,NaN,NaN,NaN
Small Pickup Trucks,NaN,NaN,21.403955,NaN,17.870588,NaN,NaN,NaN,NaN
Small Pickup Trucks 2WD,NaN,NaN,21.491667,18.062500,17.867257,16.500000,NaN,NaN,NaN
Small Pickup Trucks 4WD,NaN,NaN,19.692308,18.000000,17.000000,16.000000,NaN,NaN,NaN
Small Sport Utility Vehicle 2WD,NaN,NaN,25.055777,NaN,21.292683,NaN,NaN,NaN,NaN
Small Sport Utility Vehicle 4WD,NaN,NaN,24.185714,22.000000,20.115385,16.000000,NaN,NaN,NaN
Small Station Wagons,NaN,NaN,25.034906,22.093750,19.542986,15.923077,NaN,NaN,NaN
Special Purpose Vehicle,NaN,NaN,22.000000,NaN,NaN,NaN,NaN,NaN,NaN
Special Purpose Vehicle 2WD,NaN,NaN,20.337449,NaN,16.720524,14.018349,NaN,NaN,NaN
Special Purpose Vehicle 4WD,NaN,NaN,20.106667,NaN,16.250000,13.519481,NaN,NaN,NaN
Special Purpose Vehicles,NaN,28.000000,20.014768,NaN,16.046699,13.133117,NaN,NaN,NaN
Special Purpose Vehicles/2wd,NaN,NaN,21.000000,NaN,18.000000,NaN,NaN,NaN,NaN
Special Purpose Vehicles/4wd,NaN,NaN,NaN,NaN,17.000000,NaN,NaN,NaN,NaN
Sport Utility Vehicle - 2WD,NaN,NaN,22.549902,18.200000,18.172965,15.289538,NaN,NaN,NaN
Sport Utility Vehicle - 4WD,NaN,NaN,21.354067,17.045455,17.497441,14.443939,17.250000,NaN,NaN
Standard Pickup Trucks,NaN,NaN,19.170909,NaN,15.928158,13.815857,NaN,NaN,NaN
Standard Pickup Trucks 2WD,NaN,NaN,20.471831,18.066667,16.946970,15.258803,9.600000,NaN,NaN
Standard Pickup Trucks 4WD,NaN,NaN,18.089286,17.300000,15.887640,14.611219,NaN,NaN,NaN
Standard Pickup Trucks/2wd,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN,NaN
Standard Sport Utility Vehicle 2WD,NaN,NaN,24.153846,NaN,19.544304,16.942529,NaN,NaN,NaN
Standard Sport Utility Vehicle 4WD,NaN,NaN,23.894737,NaN,19.931937,15.873096,NaN,13.500000,NaN
Subcompact Cars,21.631579,35.335938,24.913311,20.829545,19.968631,16.590193,13.000000,13.230769,NaN
Two Seaters,17.428571,39.853659,24.940529,NaN,19.768271,16.021531,14.323529,11.860465,10.0
Vans,NaN,NaN,18.634483,15.833333,15.670683,13.453390,NaN,NaN,NaN
Vans Passenger,NaN,NaN,NaN,NaN,17.000000,12.000000,NaN,NaN,NaN
"Vans, Cargo Type",NaN,NaN,21.666667,NaN,15.152778,13.935943,12.000000,NaN,NaN
"Vans, Passenger Type",NaN,NaN,18.000000,15.000000,14.814815,13.488152,11.000000,NaN,NaN

In [33]:
df.pivot_table(index='Vehicle Class',columns='Cylinders', values='Combined MPG', aggfunc='median')

Cylinders,2.0,3.0,4.0,5.0,6.0,8.0,10.0,12.0,16.0
Vehicle Class,,,,,,,,,
Compact Cars,NaN,36.5,25.0,22.0,20.0,17.0,NaN,14.0,NaN
Large Cars,NaN,NaN,25.0,NaN,20.0,18.0,NaN,14.0,NaN
Midsize Cars,NaN,NaN,24.0,19.0,20.0,18.0,13.0,13.0,NaN
Midsize Station Wagons,NaN,NaN,22.0,20.0,19.0,17.0,NaN,NaN,NaN
Midsize-Large Station Wagons,NaN,NaN,21.0,19.0,19.0,18.0,NaN,NaN,NaN
Minicompact Cars,18.0,36.0,25.0,23.0,19.0,17.0,NaN,13.0,NaN
Minivan - 2WD,NaN,NaN,21.0,NaN,19.0,NaN,NaN,NaN,NaN
Minivan - 4WD,NaN,NaN,NaN,NaN,18.0,NaN,NaN,NaN,NaN
Small Pickup Trucks,NaN,NaN,21.0,NaN,18.0,NaN,NaN,NaN,NaN
Small Pickup Trucks 2WD,NaN,NaN,21.0,18.5,18.0,16.5,NaN,NaN,NaN
Small Pickup Trucks 4WD,NaN,NaN,20.0,18.0,17.0,16.0,NaN,NaN,NaN
Small Sport Utility Vehicle 2WD,NaN,NaN,25.0,NaN,21.0,NaN,NaN,NaN,NaN
Small Sport Utility Vehicle 4WD,NaN,NaN,24.0,22.0,20.0,16.0,NaN,NaN,NaN
Small Station Wagons,NaN,NaN,25.0,22.0,20.0,16.0,NaN,NaN,NaN
Special Purpose Vehicle,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN
Special Purpose Vehicle 2WD,NaN,NaN,20.0,NaN,17.0,14.0,NaN,NaN,NaN
Special Purpose Vehicle 4WD,NaN,NaN,20.0,NaN,16.0,13.0,NaN,NaN,NaN
Special Purpose Vehicles,NaN,28.0,20.0,NaN,16.0,13.0,NaN,NaN,NaN
Special Purpose Vehicles/2wd,NaN,NaN,21.0,NaN,18.0,NaN,NaN,NaN,NaN
Special Purpose Vehicles/4wd,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN
Sport Utility Vehicle - 2WD,NaN,NaN,22.0,18.0,18.0,15.0,NaN,NaN,NaN
Sport Utility Vehicle - 4WD,NaN,NaN,21.0,17.0,17.0,14.0,17.0,NaN,NaN
Standard Pickup Trucks,NaN,NaN,19.0,NaN,16.0,14.0,NaN,NaN,NaN
Standard Pickup Trucks 2WD,NaN,NaN,21.0,18.0,17.0,15.0,10.0,NaN,NaN
Standard Pickup Trucks 4WD,NaN,NaN,18.0,17.0,16.0,14.0,NaN,NaN,NaN
Standard Pickup Trucks/2wd,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN
Standard Sport Utility Vehicle 2WD,NaN,NaN,24.0,NaN,19.0,17.0,NaN,NaN,NaN
Standard Sport Utility Vehicle 4WD,NaN,NaN,24.0,NaN,19.0,16.0,NaN,13.5,NaN
Subcompact Cars,18.0,34.0,24.0,20.0,20.0,17.0,13.0,13.0,NaN
Two Seaters,17.0,36.0,24.0,NaN,20.0,16.0,14.0,12.0,10.0
Vans,NaN,NaN,19.0,15.5,16.0,13.0,NaN,NaN,NaN
Vans Passenger,NaN,NaN,NaN,NaN,17.0,12.0,NaN,NaN,NaN
"Vans, Cargo Type",NaN,NaN,21.0,NaN,15.0,14.0,12.0,NaN,NaN
"Vans, Passenger Type",NaN,NaN,18.0,15.0,15.0,14.0,11.0,NaN,NaN

In [34]:
df.pivot_table(index='Vehicle Class',columns='Cylinders', values='Combined MPG', aggfunc='median', fill_value=0)

Cylinders,2.0,3.0,4.0,5.0,6.0,8.0,10.0,12.0,16.0
Vehicle Class,,,,,,,,,
Compact Cars,0,36.5,25,22.0,20,17.0,0,14.0,0
Large Cars,0,0.0,25,0.0,20,18.0,0,14.0,0
Midsize Cars,0,0.0,24,19.0,20,18.0,13,13.0,0
Midsize Station Wagons,0,0.0,22,20.0,19,17.0,0,0.0,0
Midsize-Large Station Wagons,0,0.0,21,19.0,19,18.0,0,0.0,0
Minicompact Cars,18,36.0,25,23.0,19,17.0,0,13.0,0
Minivan - 2WD,0,0.0,21,0.0,19,0.0,0,0.0,0
Minivan - 4WD,0,0.0,0,0.0,18,0.0,0,0.0,0
Small Pickup Trucks,0,0.0,21,0.0,18,0.0,0,0.0,0
Small Pickup Trucks 2WD,0,0.0,21,18.5,18,16.5,0,0.0,0
Small Pickup Trucks 4WD,0,0.0,20,18.0,17,16.0,0,0.0,0
Small Sport Utility Vehicle 2WD,0,0.0,25,0.0,21,0.0,0,0.0,0
Small Sport Utility Vehicle 4WD,0,0.0,24,22.0,20,16.0,0,0.0,0
Small Station Wagons,0,0.0,25,22.0,20,16.0,0,0.0,0
Special Purpose Vehicle,0,0.0,22,0.0,0,0.0,0,0.0,0
Special Purpose Vehicle 2WD,0,0.0,20,0.0,17,14.0,0,0.0,0
Special Purpose Vehicle 4WD,0,0.0,20,0.0,16,13.0,0,0.0,0
Special Purpose Vehicles,0,28.0,20,0.0,16,13.0,0,0.0,0
Special Purpose Vehicles/2wd,0,0.0,21,0.0,18,0.0,0,0.0,0
Special Purpose Vehicles/4wd,0,0.0,0,0.0,17,0.0,0,0.0,0
Sport Utility Vehicle - 2WD,0,0.0,22,18.0,18,15.0,0,0.0,0
Sport Utility Vehicle - 4WD,0,0.0,21,17.0,17,14.0,17,0.0,0
Standard Pickup Trucks,0,0.0,19,0.0,16,14.0,0,0.0,0
Standard Pickup Trucks 2WD,0,0.0,21,18.0,17,15.0,10,0.0,0
Standard Pickup Trucks 4WD,0,0.0,18,17.0,16,14.0,0,0.0,0
Standard Pickup Trucks/2wd,0,0.0,0,0.0,0,13.0,0,0.0,0
Standard Sport Utility Vehicle 2WD,0,0.0,24,0.0,19,17.0,0,0.0,0
Standard Sport Utility Vehicle 4WD,0,0.0,24,0.0,19,16.0,0,13.5,0
Subcompact Cars,18,34.0,24,20.0,20,17.0,13,13.0,0
Two Seaters,17,36.0,24,0.0,20,16.0,14,12.0,10
Vans,0,0.0,19,15.5,16,13.0,0,0.0,0
Vans Passenger,0,0.0,0,0.0,17,12.0,0,0.0,0
"Vans, Cargo Type",0,0.0,21,0.0,15,14.0,12,0.0,0
"Vans, Passenger Type",0,0.0,18,15.0,15,14.0,11,0.0,0

In [37]:
df.pivot_table(index='Vehicle Class',values=['Combined MPG','City MPG'], aggfunc='sum', fill_value=0)

                                    City MPG  Combined MPG
Vehicle Class
Compact Cars                          106659        121191
Large Cars                             28099         32988
Midsize Cars                           76997         88047
Midsize Station Wagons                  7638          8746
Midsize-Large Station Wagons           11135         12612
Minicompact Cars                       22277         25486
Minivan - 2WD                           5521          6328
Minivan - 4WD                            725           829
Small Pickup Trucks                     9650         10615
Small Pickup Trucks 2WD                 7187          8019
Small Pickup Trucks 4WD                 3281          3625
Small Sport Utility Vehicle 2WD         7909          8908
Small Sport Utility Vehicle 4WD         9893         11076
Small Station Wagons                   29075         32684
Special Purpose Vehicle                   21            22
Special Purpose Vehicle 2WD             9291         10299
Special Purpose Vehicle 4WD             3851          4239
Special Purpose Vehicles               21490         23525
Special Purpose Vehicles/2wd              37            39
Special Purpose Vehicles/4wd              31            34
Sport Utility Vehicle - 2WD            27197         30401
Sport Utility Vehicle - 4WD            32289         35998
Standard Pickup Trucks                 31943         35224
Standard Pickup Trucks 2WD             16854         18875
Standard Pickup Trucks 4WD             13247         14742
Standard Pickup Trucks/2wd                48            52
Standard Sport Utility Vehicle 2WD      2925          3332
Standard Sport Utility Vehicle 4WD      6599          7415
Subcompact Cars                        87499         98967
Two Seaters                            30348         34813
Vans                                   15370         16951
Vans Passenger                            26            29
Vans, Cargo Type                        5571          6211
Vans, Passenger Type                    3731          4177

In [40]:
df.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [44]:
def groupmode(x):
    return x.mode().values

In [45]:
df.groupby('Year')['Vehicle Class'].agg(groupmode)

Year
1984                   Standard Pickup Trucks 2WD
1985                              Subcompact Cars
1986                              Subcompact Cars
1987                              Subcompact Cars
1988                       Standard Pickup Trucks
1989    [Standard Pickup Trucks, Subcompact Cars]
1990                       Standard Pickup Trucks
1991                              Subcompact Cars
1992                              Subcompact Cars
1993                              Subcompact Cars
1994                       Standard Pickup Trucks
1995                       Standard Pickup Trucks
1996                                 Compact Cars
1997                     Special Purpose Vehicles
1998                              Subcompact Cars
1999                                 Compact Cars
2000                                 Compact Cars
2001                                 Compact Cars
2002                                 Compact Cars
2003                                 Compact Cars
2004                                 Compact Cars
2005                                 Compact Cars
2006                  Sport Utility Vehicle - 4WD
2007                  Sport Utility Vehicle - 4WD
2008                  Sport Utility Vehicle - 4WD
2009                  Sport Utility Vehicle - 4WD
2010                  Sport Utility Vehicle - 4WD
2011                  Sport Utility Vehicle - 4WD
2012                  Sport Utility Vehicle - 4WD
2013                                 Compact Cars
2014                                 Midsize Cars
2015                                 Compact Cars
2016                                 Compact Cars
2017                                 Compact Cars
Name: Vehicle Class, dtype: object

In [46]:
df.groupby('Year')['Vehicle Class'].apply(lambda x: x.mode().values)

Year
1984                 [Standard Pickup Trucks 2WD]
1985                            [Subcompact Cars]
1986                            [Subcompact Cars]
1987                            [Subcompact Cars]
1988                     [Standard Pickup Trucks]
1989    [Standard Pickup Trucks, Subcompact Cars]
1990                     [Standard Pickup Trucks]
1991                            [Subcompact Cars]
1992                            [Subcompact Cars]
1993                            [Subcompact Cars]
1994                     [Standard Pickup Trucks]
1995                     [Standard Pickup Trucks]
1996                               [Compact Cars]
1997                   [Special Purpose Vehicles]
1998                            [Subcompact Cars]
1999                               [Compact Cars]
2000                               [Compact Cars]
2001                               [Compact Cars]
2002                               [Compact Cars]
2003                               [Compact Cars]
2004                               [Compact Cars]
2005                               [Compact Cars]
2006                [Sport Utility Vehicle - 4WD]
2007                [Sport Utility Vehicle - 4WD]
2008                [Sport Utility Vehicle - 4WD]
2009                [Sport Utility Vehicle - 4WD]
2010                [Sport Utility Vehicle - 4WD]
2011                [Sport Utility Vehicle - 4WD]
2012                [Sport Utility Vehicle - 4WD]
2013                               [Compact Cars]
2014                               [Midsize Cars]
2015                               [Compact Cars]
2016                               [Compact Cars]
2017                               [Compact Cars]
Name: Vehicle Class, dtype: object

# Lab Review

In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('D:/Downloads_new/pokemon.csv')

In [6]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [7]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [8]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [9]:
df.rename(columns={"Type 1":'t1','Type 2':'t2'},inplace=True)

In [20]:
df[['t1','t2']].apply(lambda x: tuple(set((x['t1'],x['t2']))),axis=1).values

array([('Poison', 'Grass'), ('Poison', 'Grass'), ('Poison', 'Grass'),
       ('Poison', 'Grass'), (nan, 'Fire'), (nan, 'Fire'),
       ('Fire', 'Flying'), ('Dragon', 'Fire'), ('Fire', 'Flying'),
       ('Water', nan), ('Water', nan), ('Water', nan), ('Water', nan),
       (nan, 'Bug'), (nan, 'Bug'), ('Bug', 'Flying'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), ('Bug', 'Poison'), ('Bug', 'Poison'),
       ('Normal', 'Flying'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), (nan, 'Normal'), (nan, 'Normal'),
       ('Normal', 'Flying'), ('Normal', 'Flying'), (nan, 'Poison'),
       (nan, 'Poison'), (nan, 'Electric'), (nan, 'Electric'),
       (nan, 'Ground'), (nan, 'Ground'), (nan, 'Poison'), (nan, 'Poison'),
       ('Ground', 'Poison'), (nan, 'Poison'), (nan, 'Poison'),
       ('Ground', 'Poison'), (nan, 'Fairy'), (nan, 'Fairy'),
       (nan, 'Fire'), (nan, 'Fire'), ('Normal', 'Fairy'),
       ('Normal', 'Fairy'), ('Flying', 'Poison'), ('Flying', 'Poison'),
       ('Poison', 'Grass'), ('Poison', 'Grass'), ('Poison', 'Grass'),
       ('Bug', 'Grass'), ('Bug', 'Grass'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), (nan, 'Ground'), (nan, 'Ground'),
       (nan, 'Normal'), (nan, 'Normal'), ('Water', nan), ('Water', nan),
       (nan, 'Fighting'), (nan, 'Fighting'), (nan, 'Fire'), (nan, 'Fire'),
       ('Water', nan), ('Water', nan), ('Water', 'Fighting'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Fighting'), (nan, 'Fighting'),
       (nan, 'Fighting'), ('Poison', 'Grass'), ('Poison', 'Grass'),
       ('Poison', 'Grass'), ('Water', 'Poison'), ('Water', 'Poison'),
       ('Rock', 'Ground'), ('Rock', 'Ground'), ('Rock', 'Ground'),
       (nan, 'Fire'), (nan, 'Fire'), ('Water', 'Psychic'),
       ('Water', 'Psychic'), ('Water', 'Psychic'), ('Electric', 'Steel'),
       ('Electric', 'Steel'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Water', nan), ('Water', 'Ice'),
       (nan, 'Poison'), (nan, 'Poison'), ('Water', nan), ('Water', 'Ice'),
       ('Ghost', 'Poison'), ('Ghost', 'Poison'), ('Ghost', 'Poison'),
       ('Ghost', 'Poison'), ('Rock', 'Ground'), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Water', nan), ('Water', nan),
       (nan, 'Electric'), (nan, 'Electric'), ('Psychic', 'Grass'),
       ('Psychic', 'Grass'), (nan, 'Ground'), (nan, 'Ground'),
       (nan, 'Fighting'), (nan, 'Fighting'), (nan, 'Normal'),
       (nan, 'Poison'), (nan, 'Poison'), ('Rock', 'Ground'),
       ('Rock', 'Ground'), (nan, 'Normal'), (nan, 'Grass'),
       (nan, 'Normal'), (nan, 'Normal'), ('Water', nan), ('Water', nan),
       ('Water', nan), ('Water', nan), ('Water', nan),
       ('Water', 'Psychic'), ('Psychic', 'Fairy'), ('Bug', 'Flying'),
       ('Psychic', 'Ice'), (nan, 'Electric'), (nan, 'Fire'), (nan, 'Bug'),
       ('Bug', 'Flying'), (nan, 'Normal'), ('Water', nan),
       ('Water', 'Flying'), ('Water', 'Dark'), ('Water', 'Ice'),
       (nan, 'Normal'), (nan, 'Normal'), ('Water', nan),
       (nan, 'Electric'), (nan, 'Fire'), (nan, 'Normal'),
       ('Water', 'Rock'), ('Water', 'Rock'), ('Water', 'Rock'),
       ('Water', 'Rock'), ('Rock', 'Flying'), ('Rock', 'Flying'),
       (nan, 'Normal'), ('Ice', 'Flying'), ('Electric', 'Flying'),
       ('Fire', 'Flying'), (nan, 'Dragon'), (nan, 'Dragon'),
       ('Dragon', 'Flying'), (nan, 'Psychic'), ('Psychic', 'Fighting'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Grass'), (nan, 'Grass'),
       (nan, 'Grass'), (nan, 'Fire'), (nan, 'Fire'), (nan, 'Fire'),
       ('Water', nan), ('Water', nan), ('Water', nan), (nan, 'Normal'),
       (nan, 'Normal'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Bug', 'Flying'), ('Bug', 'Flying'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), ('Flying', 'Poison'), ('Water', 'Electric'),
       ('Water', 'Electric'), (nan, 'Electric'), (nan, 'Fairy'),
       ('Normal', 'Fairy'), (nan, 'Fairy'), ('Fairy', 'Flying'),
       ('Psychic', 'Flying'), ('Psychic', 'Flying'), (nan, 'Electric'),
       (nan, 'Electric'), (nan, 'Electric'), ('Dragon', 'Electric'),
       (nan, 'Grass'), ('Water', 'Fairy'), ('Water', 'Fairy'),
       (nan, 'Rock'), ('Water', nan), ('Flying', 'Grass'),
       ('Flying', 'Grass'), ('Flying', 'Grass'), (nan, 'Normal'),
       (nan, 'Grass'), (nan, 'Grass'), ('Bug', 'Flying'),
       ('Water', 'Ground'), ('Water', 'Ground'), (nan, 'Psychic'),
       (nan, 'Dark'), ('Dark', 'Flying'), ('Water', 'Psychic'),
       (nan, 'Ghost'), (nan, 'Psychic'), (nan, 'Psychic'),
       ('Psychic', 'Normal'), (nan, 'Bug'), ('Bug', 'Steel'),
       (nan, 'Normal'), ('Ground', 'Flying'), ('Ground', 'Steel'),
       ('Ground', 'Steel'), (nan, 'Fairy'), (nan, 'Fairy'),
       ('Water', 'Poison'), ('Bug', 'Steel'), ('Bug', 'Steel'),
       ('Rock', 'Bug'), ('Fighting', 'Bug'), ('Fighting', 'Bug'),
       ('Dark', 'Ice'), (nan, 'Normal'), (nan, 'Normal'), (nan, 'Fire'),
       ('Rock', 'Fire'), ('Ground', 'Ice'), ('Ground', 'Ice'),
       ('Water', 'Rock'), ('Water', nan), ('Water', nan),
       ('Ice', 'Flying'), ('Water', 'Flying'), ('Flying', 'Steel'),
       ('Dark', 'Fire'), ('Dark', 'Fire'), ('Dark', 'Fire'),
       ('Water', 'Dragon'), (nan, 'Ground'), (nan, 'Ground'),
       (nan, 'Normal'), (nan, 'Normal'), (nan, 'Normal'),
       (nan, 'Fighting'), (nan, 'Fighting'), ('Psychic', 'Ice'),
       (nan, 'Electric'), (nan, 'Fire'), (nan, 'Normal'), (nan, 'Normal'),
       (nan, 'Electric'), (nan, 'Fire'), ('Water', nan),
       ('Rock', 'Ground'), ('Rock', 'Ground'), ('Dark', 'Rock'),
       ('Dark', 'Rock'), ('Psychic', 'Flying'), ('Fire', 'Flying'),
       ('Psychic', 'Grass'), (nan, 'Grass'), (nan, 'Grass'),
       (nan, 'Grass'), ('Dragon', 'Grass'), (nan, 'Fire'),
       ('Fighting', 'Fire'), ('Fighting', 'Fire'), ('Fighting', 'Fire'),
       ('Water', nan), ('Water', 'Ground'), ('Water', 'Ground'),
       ('Water', 'Ground'), (nan, 'Dark'), (nan, 'Dark'), (nan, 'Normal'),
       (nan, 'Normal'), (nan, 'Bug'), (nan, 'Bug'), ('Bug', 'Flying'),
       (nan, 'Bug'), ('Bug', 'Poison'), ('Water', 'Grass'),
       ('Water', 'Grass'), ('Water', 'Grass'), (nan, 'Grass'),
       ('Dark', 'Grass'), ('Dark', 'Grass'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Water', 'Flying'), ('Water', 'Flying'),
       ('Psychic', 'Fairy'), ('Psychic', 'Fairy'), ('Psychic', 'Fairy'),
       ('Psychic', 'Fairy'), ('Water', 'Bug'), ('Bug', 'Flying'),
       (nan, 'Grass'), ('Fighting', 'Grass'), (nan, 'Normal'),
       (nan, 'Normal'), (nan, 'Normal'), ('Ground', 'Bug'),
       ('Bug', 'Flying'), ('Ghost', 'Bug'), (nan, 'Normal'),
       (nan, 'Normal'), (nan, 'Normal'), (nan, 'Fighting'),
       (nan, 'Fighting'), ('Normal', 'Fairy'), (nan, 'Rock'),
       (nan, 'Normal'), (nan, 'Normal'), ('Ghost', 'Dark'),
       ('Ghost', 'Dark'), ('Fairy', 'Steel'), ('Fairy', 'Steel'),
       ('Rock', 'Steel'), ('Rock', 'Steel'), ('Rock', 'Steel'),
       (nan, 'Steel'), ('Psychic', 'Fighting'), ('Psychic', 'Fighting'),
       ('Psychic', 'Fighting'), (nan, 'Electric'), (nan, 'Electric'),
       (nan, 'Electric'), (nan, 'Electric'), (nan, 'Electric'),
       (nan, 'Bug'), (nan, 'Bug'), ('Poison', 'Grass'), (nan, 'Poison'),
       (nan, 'Poison'), ('Water', 'Dark'), ('Water', 'Dark'),
       ('Water', 'Dark'), ('Water', nan), ('Water', nan),
       ('Ground', 'Fire'), ('Ground', 'Fire'), ('Ground', 'Fire'),
       (nan, 'Fire'), (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Normal'),
       (nan, 'Ground'), ('Dragon', 'Ground'), ('Dragon', 'Ground'),
       (nan, 'Grass'), ('Dark', 'Grass'), ('Normal', 'Flying'),
       ('Dragon', 'Flying'), ('Fairy', 'Dragon'), (nan, 'Normal'),
       (nan, 'Poison'), ('Psychic', 'Rock'), ('Psychic', 'Rock'),
       ('Water', 'Ground'), ('Water', 'Ground'), ('Water', nan),
       ('Water', 'Dark'), ('Psychic', 'Ground'), ('Psychic', 'Ground'),
       ('Rock', 'Grass'), ('Rock', 'Grass'), ('Rock', 'Bug'),
       ('Rock', 'Bug'), ('Water', nan), ('Water', nan), (nan, 'Normal'),
       (nan, 'Normal'), (nan, 'Ghost'), (nan, 'Ghost'), (nan, 'Ghost'),
       (nan, 'Ghost'), (nan, 'Ghost'), ('Flying', 'Grass'),
       (nan, 'Psychic'), (nan, 'Dark'), (nan, 'Dark'), (nan, 'Psychic'),
       (nan, 'Ice'), (nan, 'Ice'), (nan, 'Ice'), ('Water', 'Ice'),
       ('Water', 'Ice'), ('Water', 'Ice'), ('Water', nan), ('Water', nan),
       ('Water', nan), ('Water', 'Rock'), ('Water', nan), (nan, 'Dragon'),
       (nan, 'Dragon'), ('Dragon', 'Flying'), ('Dragon', 'Flying'),
       ('Psychic', 'Steel'), ('Psychic', 'Steel'), ('Psychic', 'Steel'),
       ('Psychic', 'Steel'), (nan, 'Rock'), (nan, 'Ice'), (nan, 'Steel'),
       ('Psychic', 'Dragon'), ('Psychic', 'Dragon'),
       ('Psychic', 'Dragon'), ('Psychic', 'Dragon'), ('Water', nan),
       ('Water', nan), (nan, 'Ground'), ('Ground', 'Fire'),
       ('Dragon', 'Flying'), ('Dragon', 'Flying'), ('Psychic', 'Steel'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Grass'), (nan, 'Grass'),
       ('Ground', 'Grass'), (nan, 'Fire'), ('Fighting', 'Fire'),
       ('Fighting', 'Fire'), ('Water', nan), ('Water', nan),
       ('Water', 'Steel'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), (nan, 'Normal'), ('Water', 'Normal'),
       (nan, 'Bug'), (nan, 'Bug'), (nan, 'Electric'), (nan, 'Electric'),
       (nan, 'Electric'), ('Poison', 'Grass'), ('Poison', 'Grass'),
       (nan, 'Rock'), (nan, 'Rock'), ('Rock', 'Steel'), ('Rock', 'Steel'),
       (nan, 'Bug'), ('Bug', 'Grass'), ('Ground', 'Bug'),
       ('Bug', 'Steel'), ('Bug', 'Flying'), ('Bug', 'Flying'),
       ('Bug', 'Flying'), (nan, 'Electric'), ('Water', nan),
       ('Water', nan), (nan, 'Grass'), (nan, 'Grass'), ('Water', nan),
       ('Water', 'Ground'), (nan, 'Normal'), ('Ghost', 'Flying'),
       ('Ghost', 'Flying'), (nan, 'Normal'), (nan, 'Normal'),
       ('Normal', 'Fighting'), (nan, 'Ghost'), ('Dark', 'Flying'),
       (nan, 'Normal'), (nan, 'Normal'), (nan, 'Psychic'),
       ('Dark', 'Poison'), ('Dark', 'Poison'), ('Psychic', 'Steel'),
       ('Psychic', 'Steel'), (nan, 'Rock'), ('Psychic', 'Fairy'),
       (nan, 'Normal'), ('Normal', 'Flying'), ('Dark', 'Ghost'),
       ('Dragon', 'Ground'), ('Dragon', 'Ground'), ('Dragon', 'Ground'),
       ('Dragon', 'Ground'), (nan, 'Normal'), (nan, 'Fighting'),
       ('Fighting', 'Steel'), ('Fighting', 'Steel'), (nan, 'Ground'),
       (nan, 'Ground'), ('Bug', 'Poison'), ('Dark', 'Poison'),
       ('Fighting', 'Poison'), ('Fighting', 'Poison'), (nan, 'Grass'),
       ('Water', nan), ('Water', nan), ('Water', 'Flying'),
       ('Ice', 'Grass'), ('Ice', 'Grass'), ('Ice', 'Grass'),
       ('Dark', 'Ice'), ('Electric', 'Steel'), (nan, 'Normal'),
       ('Rock', 'Ground'), (nan, 'Grass'), (nan, 'Electric'),
       (nan, 'Fire'), ('Fairy', 'Flying'), ('Bug', 'Flying'),
       (nan, 'Grass'), (nan, 'Ice'), ('Ground', 'Flying'),
       ('Ground', 'Ice'), (nan, 'Normal'), ('Psychic', 'Fighting'),
       ('Psychic', 'Fighting'), ('Rock', 'Steel'), (nan, 'Ghost'),
       ('Ghost', 'Ice'), ('Ghost', 'Electric'), ('Electric', 'Fire'),
       ('Water', 'Electric'), ('Electric', 'Ice'), ('Electric', 'Flying'),
       ('Electric', 'Grass'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Dragon', 'Steel'), ('Water', 'Dragon'),
       ('Fire', 'Steel'), (nan, 'Normal'), ('Dragon', 'Ghost'),
       ('Dragon', 'Ghost'), (nan, 'Psychic'), ('Water', nan),
       ('Water', nan), (nan, 'Dark'), (nan, 'Grass'), ('Flying', 'Grass'),
       (nan, 'Normal'), ('Psychic', 'Fire'), (nan, 'Grass'),
       (nan, 'Grass'), (nan, 'Grass'), (nan, 'Fire'),
       ('Fighting', 'Fire'), ('Fighting', 'Fire'), ('Water', nan),
       ('Water', nan), ('Water', nan), (nan, 'Normal'), (nan, 'Normal'),
       (nan, 'Normal'), (nan, 'Normal'), (nan, 'Normal'), (nan, 'Dark'),
       (nan, 'Dark'), (nan, 'Grass'), (nan, 'Grass'), (nan, 'Fire'),
       (nan, 'Fire'), ('Water', nan), ('Water', nan), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Normal', 'Flying'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), (nan, 'Electric'), (nan, 'Electric'),
       (nan, 'Rock'), (nan, 'Rock'), (nan, 'Rock'), ('Psychic', 'Flying'),
       ('Psychic', 'Flying'), (nan, 'Ground'), ('Ground', 'Steel'),
       (nan, 'Normal'), ('Normal', 'Fairy'), (nan, 'Fighting'),
       (nan, 'Fighting'), (nan, 'Fighting'), ('Water', nan),
       ('Water', 'Ground'), ('Water', 'Ground'), (nan, 'Fighting'),
       (nan, 'Fighting'), ('Bug', 'Grass'), ('Bug', 'Grass'),
       ('Bug', 'Grass'), ('Bug', 'Poison'), ('Bug', 'Poison'),
       ('Bug', 'Poison'), ('Fairy', 'Grass'), ('Fairy', 'Grass'),
       (nan, 'Grass'), (nan, 'Grass'), ('Water', nan), ('Dark', 'Ground'),
       ('Dark', 'Ground'), ('Dark', 'Ground'), (nan, 'Fire'),
       (nan, 'Fire'), ('Psychic', 'Fire'), (nan, 'Grass'),
       ('Rock', 'Bug'), ('Rock', 'Bug'), ('Fighting', 'Dark'),
       ('Fighting', 'Dark'), ('Psychic', 'Flying'), (nan, 'Ghost'),
       (nan, 'Ghost'), ('Water', 'Rock'), ('Water', 'Rock'),
       ('Rock', 'Flying'), ('Rock', 'Flying'), (nan, 'Poison'),
       (nan, 'Poison'), (nan, 'Dark'), (nan, 'Dark'), (nan, 'Normal'),
       (nan, 'Normal'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       (nan, 'Psychic'), ('Water', 'Flying'), ('Water', 'Flying'),
       (nan, 'Ice'), (nan, 'Ice'), (nan, 'Ice'), ('Normal', 'Grass'),
       ('Normal', 'Grass'), ('Electric', 'Flying'), (nan, 'Bug'),
       ('Bug', 'Steel'), ('Poison', 'Grass'), ('Poison', 'Grass'),
       ('Water', 'Ghost'), ('Water', 'Ghost'), ('Water', nan),
       ('Electric', 'Bug'), ('Electric', 'Bug'), ('Steel', 'Grass'),
       ('Steel', 'Grass'), (nan, 'Steel'), (nan, 'Steel'), (nan, 'Steel'),
       (nan, 'Electric'), (nan, 'Electric'), (nan, 'Electric'),
       (nan, 'Psychic'), (nan, 'Psychic'), ('Ghost', 'Fire'),
       ('Ghost', 'Fire'), ('Ghost', 'Fire'), (nan, 'Dragon'),
       (nan, 'Dragon'), (nan, 'Dragon'), (nan, 'Ice'), (nan, 'Ice'),
       (nan, 'Ice'), (nan, 'Bug'), (nan, 'Bug'), ('Electric', 'Ground'),
       (nan, 'Fighting'), (nan, 'Fighting'), (nan, 'Dragon'),
       ('Ghost', 'Ground'), ('Ghost', 'Ground'), ('Dark', 'Steel'),
       ('Dark', 'Steel'), (nan, 'Normal'), ('Normal', 'Flying'),
       ('Normal', 'Flying'), ('Dark', 'Flying'), ('Dark', 'Flying'),
       (nan, 'Fire'), ('Bug', 'Steel'), ('Dragon', 'Dark'),
       ('Dragon', 'Dark'), ('Dragon', 'Dark'), ('Fire', 'Bug'),
       ('Fire', 'Bug'), ('Fighting', 'Steel'), ('Fighting', 'Rock'),
       ('Fighting', 'Grass'), (nan, 'Flying'), (nan, 'Flying'),
       ('Electric', 'Flying'), ('Electric', 'Flying'), ('Dragon', 'Fire'),
       ('Dragon', 'Electric'), ('Ground', 'Flying'), ('Ground', 'Flying'),
       ('Dragon', 'Ice'), ('Dragon', 'Ice'), ('Dragon', 'Ice'),
       ('Water', 'Fighting'), ('Water', 'Fighting'),
       ('Psychic', 'Normal'), ('Normal', 'Fighting'), ('Bug', 'Steel'),
       (nan, 'Grass'), (nan, 'Grass'), ('Fighting', 'Grass'),
       (nan, 'Fire'), (nan, 'Fire'), ('Psychic', 'Fire'), ('Water', nan),
       ('Water', nan), ('Water', 'Dark'), (nan, 'Normal'),
       ('Normal', 'Ground'), ('Normal', 'Flying'), ('Fire', 'Flying'),
       ('Fire', 'Flying'), (nan, 'Bug'), (nan, 'Bug'), ('Bug', 'Flying'),
       ('Normal', 'Fire'), ('Normal', 'Fire'), (nan, 'Fairy'),
       (nan, 'Fairy'), (nan, 'Fairy'), (nan, 'Grass'), (nan, 'Grass'),
       (nan, 'Fighting'), ('Dark', 'Fighting'), (nan, 'Normal'),
       (nan, 'Psychic'), (nan, 'Psychic'), (nan, 'Psychic'),
       ('Ghost', 'Steel'), ('Ghost', 'Steel'), ('Ghost', 'Steel'),
       ('Ghost', 'Steel'), (nan, 'Fairy'), (nan, 'Fairy'), (nan, 'Fairy'),
       (nan, 'Fairy'), ('Psychic', 'Dark'), ('Psychic', 'Dark'),
       ('Water', 'Rock'), ('Water', 'Rock'), ('Water', 'Poison'),
       ('Dragon', 'Poison'), ('Water', nan), ('Water', nan),
       ('Normal', 'Electric'), ('Normal', 'Electric'), ('Dragon', 'Rock'),
       ('Dragon', 'Rock'), ('Rock', 'Ice'), ('Rock', 'Ice'),
       (nan, 'Fairy'), ('Fighting', 'Flying'), ('Fairy', 'Electric'),
       ('Fairy', 'Rock'), (nan, 'Dragon'), (nan, 'Dragon'),
       (nan, 'Dragon'), ('Fairy', 'Steel'), ('Ghost', 'Grass'),
       ('Ghost', 'Grass'), ('Ghost', 'Grass'), ('Ghost', 'Grass'),
       ('Ghost', 'Grass'), ('Ghost', 'Grass'), ('Ghost', 'Grass'),
       ('Ghost', 'Grass'), ('Ghost', 'Grass'), ('Ghost', 'Grass'),
       (nan, 'Ice'), (nan, 'Ice'), ('Dragon', 'Flying'),
       ('Dragon', 'Flying'), (nan, 'Fairy'), ('Dark', 'Flying'),
       ('Dragon', 'Ground'), ('Fairy', 'Rock'), ('Fairy', 'Rock'),
       ('Psychic', 'Ghost'), ('Psychic', 'Dark'), ('Water', 'Fire')],
      dtype=object)

In [24]:
import numpy as np

In [83]:
df[['t1','t2']].applymap(str).apply(lambda x: ('nan') if (x.t1=='nan')&(x.t2=='nan') else
                                (x.t1) if (x.t1!='nan') & (x.t2=='nan') else
                                (x.t2) if (x.t1=='nan') & (x.t2!='nan') else
                                sorted((x.t1,x.t2)),axis=1).apply(str).unique()

array(["['Grass', 'Poison']", 'Fire', "['Fire', 'Flying']",
       "['Dragon', 'Fire']", 'Water', 'Bug', "['Bug', 'Flying']",
       "['Bug', 'Poison']", "['Flying', 'Normal']", 'Normal', 'Poison',
       'Electric', 'Ground', "['Ground', 'Poison']", 'Fairy',
       "['Fairy', 'Normal']", "['Flying', 'Poison']", "['Bug', 'Grass']",
       'Fighting', "['Fighting', 'Water']", 'Psychic',
       "['Poison', 'Water']", "['Ground', 'Rock']",
       "['Psychic', 'Water']", "['Electric', 'Steel']",
       "['Ice', 'Water']", "['Ghost', 'Poison']", "['Grass', 'Psychic']",
       'Grass', "['Fairy', 'Psychic']", "['Ice', 'Psychic']",
       "['Flying', 'Water']", "['Dark', 'Water']", "['Rock', 'Water']",
       "['Flying', 'Rock']", "['Flying', 'Ice']",
       "['Electric', 'Flying']", 'Dragon', "['Dragon', 'Flying']",
       "['Fighting', 'Psychic']", "['Electric', 'Water']",
       "['Fairy', 'Flying']", "['Flying', 'Psychic']",
       "['Dragon', 'Electric']", "['Fairy', 'Water']", 'Rock',
       "['Flying', 'Grass']", "['Ground', 'Water']", 'Dark',
       "['Dark', 'Flying']", 'Ghost', "['Normal', 'Psychic']",
       "['Bug', 'Steel']", "['Flying', 'Ground']", "['Ground', 'Steel']",
       "['Bug', 'Rock']", "['Bug', 'Fighting']", "['Dark', 'Ice']",
       "['Fire', 'Rock']", "['Ground', 'Ice']", "['Flying', 'Steel']",
       "['Dark', 'Fire']", "['Dragon', 'Water']", "['Dark', 'Rock']",
       "['Dragon', 'Grass']", "['Fighting', 'Fire']",
       "['Grass', 'Water']", "['Dark', 'Grass']", "['Bug', 'Water']",
       "['Fighting', 'Grass']", "['Bug', 'Ground']", "['Bug', 'Ghost']",
       "['Dark', 'Ghost']", "['Fairy', 'Steel']", "['Rock', 'Steel']",
       'Steel', "['Fire', 'Ground']", "['Dragon', 'Ground']",
       "['Dragon', 'Fairy']", "['Psychic', 'Rock']",
       "['Ground', 'Psychic']", "['Grass', 'Rock']", 'Ice',
       "['Psychic', 'Steel']", "['Dragon', 'Psychic']",
       "['Grass', 'Ground']", "['Steel', 'Water']", "['Normal', 'Water']",
       "['Flying', 'Ghost']", "['Fighting', 'Normal']",
       "['Dark', 'Poison']", "['Fighting', 'Steel']",
       "['Fighting', 'Poison']", "['Grass', 'Ice']", "['Ghost', 'Ice']",
       "['Electric', 'Ghost']", "['Electric', 'Fire']",
       "['Electric', 'Ice']", "['Electric', 'Grass']",
       "['Dragon', 'Steel']", "['Fire', 'Steel']", "['Dragon', 'Ghost']",
       "['Fire', 'Psychic']", "['Fairy', 'Grass']", "['Dark', 'Ground']",
       "['Dark', 'Fighting']", "['Grass', 'Normal']",
       "['Ghost', 'Water']", "['Bug', 'Electric']", "['Grass', 'Steel']",
       "['Fire', 'Ghost']", "['Electric', 'Ground']",
       "['Ghost', 'Ground']", "['Dark', 'Steel']", "['Dark', 'Dragon']",
       "['Bug', 'Fire']", "['Fighting', 'Rock']", 'Flying',
       "['Dragon', 'Ice']", "['Ground', 'Normal']", "['Fire', 'Normal']",
       "['Ghost', 'Steel']", "['Dark', 'Psychic']",
       "['Dragon', 'Poison']", "['Electric', 'Normal']",
       "['Dragon', 'Rock']", "['Ice', 'Rock']", "['Fighting', 'Flying']",
       "['Electric', 'Fairy']", "['Fairy', 'Rock']", "['Ghost', 'Grass']",
       "['Ghost', 'Psychic']", "['Fire', 'Water']"], dtype=object)

In [52]:
set(df.t1.to_list()+df.t2.to_list())

{'Bug',
 'Dark',
 'Dragon',
 'Electric',
 'Fairy',
 'Fighting',
 'Fire',
 'Flying',
 'Ghost',
 'Grass',
 'Ground',
 'Ice',
 'Normal',
 'Poison',
 'Psychic',
 'Rock',
 'Steel',
 'Water',
 nan}

In [54]:
set(df.t1).union(set(df.t2))

{'Bug',
 'Dark',
 'Dragon',
 'Electric',
 'Fairy',
 'Fighting',
 'Fire',
 'Flying',
 'Ghost',
 'Grass',
 'Ground',
 'Ice',
 'Normal',
 'Poison',
 'Psychic',
 'Rock',
 'Steel',
 'Water',
 nan}

In [60]:
set(df[['t1','t2']].values.ravel())

{'Bug',
 'Dark',
 'Dragon',
 'Electric',
 'Fairy',
 'Fighting',
 'Fire',
 'Flying',
 'Ghost',
 'Grass',
 'Ground',
 'Ice',
 'Normal',
 'Poison',
 'Psychic',
 'Rock',
 'Steel',
 'Water',
 nan}

In [61]:
pd.unique(df[['t1','t2']].values.ravel())

array(['Grass', 'Poison', 'Fire', nan, 'Flying', 'Dragon', 'Water', 'Bug',
       'Normal', 'Electric', 'Ground', 'Fairy', 'Fighting', 'Psychic',
       'Rock', 'Steel', 'Ice', 'Ghost', 'Dark'], dtype=object)

In [75]:
df.Name.str.split('Mega ').apply(lambda x: f'Mega {x[-1]}' if len(x)>1 else x[-1]);

In [76]:
df.Name.map(str).str.split('Mega ').apply(lambda x: 'Mega '+x[-1] if len(x)>1 else x[-1]);

In [77]:
df['AD_ratio']=df.Attack/df.Defense

In [82]:
df.iloc[df.AD_ratio.idxmax()]

#                            386
Name          DeoxysAttack Forme
t1                       Psychic
t2                           NaN
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
AD_ratio                       9
Name: 429, dtype: object

In [81]:
df.loc[df.AD_ratio.idxmin()]

#                   213
Name            Shuckle
t1                  Bug
t2                 Rock
Total               505
HP                   20
Attack               10
Defense             230
Sp. Atk              10
Sp. Def             230
Speed                 5
Generation            2
Legendary         False
AD_ratio      0.0434783
Name: 230, dtype: object

In [87]:
df['Combo_Type']=df[['t1','t2']].applymap(str).apply(lambda x: 'nan' if (x.t1=='nan')&(x.t2=='nan') else
                                x.t1 if (x.t1!='nan') & (x.t2=='nan') else
                                x.t2 if (x.t1=='nan') & (x.t2!='nan') else
                                '-'.join(sorted((x.t1,x.t2))),axis=1)

In [88]:
df.head()

,#,Name,t1,t2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,AD_ratio,Combo_Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire

In [91]:
df.loc[df.AD_ratio.nlargest(5).index]

,#,Name,t1,t2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,AD_ratio,Combo_Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Dark-Water
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Dark-Water

In [97]:
max_values=sorted(df.AD_ratio.unique())[-5:]

In [99]:
df[df.AD_ratio.isin(max_values)]

,#,Name,t1,t2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,AD_ratio,Combo_Type
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Dark-Water
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Dark-Water
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,3.000,Psychic
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False,3.000,Ghost-Steel

In [105]:
top5=list(df[df.AD_ratio.isin(max_values)].Combo_Type.unique())

In [110]:
df[df.Combo_Type.isin(top5)].groupby('Combo_Type').mean()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,AD_ratio
Combo_Type,,,,,,,,,,,
Bug-Poison,218.538462,346.538462,52.692308,66.923077,60.538462,41.538462,59.000000,65.846154,2.461538,0.000000,1.257494
Dark-Water,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949
Ghost-Steel,680.250000,453.250000,56.000000,97.500000,112.500000,70.000000,71.500000,45.750000,6.000000,0.000000,1.216667
Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196
Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091

In [119]:
(df[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']].sum(axis=1)-df.Total).abs().sum()

0

In [120]:
df

,#,Name,t1,t2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,AD_ratio,Combo_Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,Fairy-Rock
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,Fairy-Rock
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,Ghost-Psychic
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,Dark-Psychic
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,Fire-Water

In [124]:
dummies=pd.get_dummies(df.t1)+pd.get_dummies(df.t2)

In [135]:
df1=pd.concat([df,dummies],axis=1)

In [133]:
df[['t1','t2']].stack().str.get_dummies()

        Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  \
0   t1    0     0       0         0      0         0     0       0      0
    t2    0     0       0         0      0         0     0       0      0
1   t1    0     0       0         0      0         0     0       0      0
    t2    0     0       0         0      0         0     0       0      0
2   t1    0     0       0         0      0         0     0       0      0
...     ...   ...     ...       ...    ...       ...   ...     ...    ...
797 t2    0     0       0         0      0         0     0       0      1
798 t1    0     0       0         0      0         0     0       0      0
    t2    0     1       0         0      0         0     0       0      0
799 t1    0     0       0         0      0         0     1       0      0
    t2    0     0       0         0      0         0     0       0      0

        Grass  Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water
0   t1      1       0    0       0       0        0     0      0      0
    t2      0       0    0       0       1        0     0      0      0
1   t1      1       0    0       0       0        0     0      0      0
    t2      0       0    0       0       1        0     0      0      0
2   t1      1       0    0       0       0        0     0      0      0
...       ...     ...  ...     ...     ...      ...   ...    ...    ...
797 t2      0       0    0       0       0        0     0      0      0
798 t1      0       0    0       0       0        1     0      0      0
    t2      0       0    0       0       0        0     0      0      0
799 t1      0       0    0       0       0        0     0      0      0
    t2      0       0    0       0       0        0     0      0      1

[1214 rows x 18 columns]

In [163]:
df1[list(df1.columns[-18:])+['Total']].corr()['Total'].sort_values(ascending=False).iloc[1:6]

Dragon      0.229705
Psychic     0.124688
Steel       0.109703
Fire        0.078726
Fighting    0.077786
Name: Total, dtype: float64

In [166]:
vs=df1[list(df1.columns[-18:])+['Total']]

In [172]:
vs[vs['Dragon']==1].corr()['Total'].sort_values(ascending=False)[1:6]

Ice         0.258348
Psychic     0.225239
Ghost       0.199128
Fire        0.165998
Electric    0.148712
Name: Total, dtype: float64